### ISSUE TITLE
ACC widget stuttering caused by continuous WebSocket exceptions

### ISSUE THREAD

**Issue by WraithStar** [SHWotever/SimHub#1099]
**Describe the bug**
Heavy stuttering on all the widgets when playing ACC

**Simhub version**
8.0.1

**To Reproduce**
1. Play ACC
2. Observe all the dashes getting insane stutters

**Expected behavior**
No stuttering

**Screenshots**
N/A

**Log files**
```
[2022-06-04` 16:57:41,170] ERROR - System.AggregateException: One or more errors occurred. ---> System.Net.WebSockets.WebSocketException: The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.Plugins.Web.CoreWebSocketListenerWrap.<SendString>d__23.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at SimHub.Plugins.Web.CoreWebSocketListenerWrap.SendObject(Int64 pid, Object message)
   at SimHub.Plugins.Web.RemoteDash.SendObjectInternal(Object message)
   at SimHub.Plugins.Web.RemoteDash.componentsUpdated(Object p)
   at SimHub.Plugins.Web.WebPlugin.UpdateComponents(GameData& data)
   at SimHub.Plugins.Web.WebPlugin.DataUpdate(PluginManager pluginManager, GameData& data)
   at SimHub.Plugins.PluginManager.<>c__DisplayClass220_2.<manager_DataUpdated>b__1()
   at SimHub.Plugins.PluginManager.ExecUpdate(PluginInstance plugin, Action a)
---> (Inner Exception #0) System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.Plugins.Web.CoreWebSocketListenerWrap.<SendString>d__23.MoveNext()<---
```

**Additional context**
Seems to be caused by constant websocket exceptions

**Comment by SHWotever** [comment]
Hi ! Could you join the full log file ? it will help to see the whole context.

**Comment by WraithStar** [comment]
[SimHub.log.20.zip](https://github.com/SHWotever/SimHub/files/8886144/SimHub.log.20.zip)

Here, but there isn't really much else. You'll see I'm running my own plugin but I'm 100% sure that plugin is not the cause of the issue, because on RF2 and AC the stuttering is not a thing. And of course I'm not getting the WebSocket exception there.

**Comment by SHWotever** [comment]
Hi ! I see that the  browser is suddenly stopping rendering and freezing. From the log i can see that it's not a common browser bu a custom embedded one : twitch-desktop-electron-platform/1.0.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36 spotlight/0.109.9


As a workaround you can disable the data update control in the settings : 
![image](https://user-images.githubusercontent.com/2207331/184527713-a5c79413-003f-4dd0-b8cc-76ccc2096f24.png)

This will ignore the fact that the dash is frozen on browser side, it could help.
