### ISSUE TITLE
USBD480 Freeze

### ISSUE THREAD

**Issue by Racing91** [SHWotever/SimHub#1264]
Having an issue with a USBD480 display freezing after a while, any idea where to look?

[2023-03-27 13:55:14,299] ERROR - System.Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: USBD480 Exception0
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplay.USBD480.Wrapper.Check(Int32 result)
   at SimHub.BitmapDisplay.USBD480.USBD480Service.Draw(DrawRequest drawRequest)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SimHub.BitmapDisplay.Core.PipeBitmapDisplayClient`1.PipeClient_ServerMessage(NamedPipeConnection`2 connection, String message)
   at SimHub.BitmapDisplay.Core.PipeServerBase.WaitForResult[T](Func`1 action)
   at SimHub.BitmapDisplay.Core.PipeServerBase.InvokeWithParameters[T](Object parameters, String memberName)
   at SimHub.BitmapDisplay.Core.PipeBitmapDisplayServer.Draw(DrawRequest drawRequest)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.RemoteDisplayManagerBase`3.Draw()
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplay.USBD480.RemoteUSBD480Manager.SendBitmap(Bitmap bmp, Boolean flipDisplay)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplayBase.SendPicture()

**Comment by SHWotever** [comment]
Hi ! Exception 0 means that the usb connection is failing, here is a few potential causes : 
- Please make sure to avoid usb hubs if you use some as well as your usb cable. 
- Sometimes some usb ports can cause troubles due to heavy bandwidth (usb sound card/headset). 
- Trying another usb port on the mother board can help. 
- Overall usbd480 is not supporting very well usb3 ports, switching to an usb2.0 can help too.
- Lowering brightness can help too if usb power is a tad too low.

Let me know if it helped,

**Comment by Racing91** [comment]
Thanks! Will look into it!
