### ISSUE TITLE
Decompressing ArduinoIDE stuck since SimHub 3.8.4

### ISSUE THREAD

**Issue by westang78** [SHWotever/SimHub#1292]
**Describe the bug**
My Simhub stuck in "Decompressing SimHub.ArduinoIDE.1.0.0.7z" after I click to "Open arduino setup tool"

**Simhub version**
SimHub 8.3.9

**To Reproduce**
1. Go to 'Arduino'
2. Click on 'My Hardware'
3. Select 'Open arduino setup tool'
4. A window pop-up "Decompressing SimHub.ArduinoIDE.1.0.0.7z" and stuck, no progess at all.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/132046097/235076776-74909910-55fb-4d20-ba3d-820279c4a4c1.png)

**Log files**
[2023-04-28 13:48:24,891] INFO - Starting SimHub v8.3.9 (build time : 25/04/2023 00:45:40)
[2023-04-28 13:48:24,891] INFO - Administrator privileges : True 
[2023-04-28 13:48:24,891] INFO - OS version : Microsoft Windows NT 10.0.19045.0, Windows 10.0.19045
[2023-04-28 13:48:24,891] INFO - License status : Free
[2023-04-28 13:48:24,891] INFO - Process priority : Normal
[2023-04-28 13:48:25,547] INFO - 77 game readers loaded
[2023-04-28 13:48:27,719] INFO - (Re)Starting AssettoCorsa Game Manager and plugin manager
[2023-04-28 13:48:27,719] INFO - Creating Assetto Corsa game manager (ACSharedMemory.ACManager)
[2023-04-28 13:48:27,766] INFO - AssettoCorsa game manager created
[2023-04-28 13:48:27,797] INFO - Checking configuration status for AssettoCorsa
[2023-04-28 13:48:27,797] INFO - Detected install path : None
[2023-04-28 13:48:27,797] INFO - Configuration status for AssettoCorsa: GameNotDetected
[2023-04-28 13:48:27,797] INFO - Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, DevicesPlugin, KeyboardEmulatorPlugin, KeyboardReaderPlugin, IRacingExtraProperties, ShakeITBSV3Plugin, ShakeITMotorsV3Plugin, ShakeItWindPlugin, LapHitoryPlugin, ThrustmastersPlugin
[2023-04-28 13:48:27,953] INFO - Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2023-04-28 13:48:27,953] INFO - Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2023-04-28 13:48:27,953] INFO - Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2023-04-28 13:48:27,953] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2023-04-28 13:48:27,969] INFO - Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2023-04-28 13:48:27,969] INFO - Creating SimHub.Plugins.Web.WebPlugin plugin
[2023-04-28 13:48:27,969] INFO - Creating RSC.iRacingExtraProperties.IRacingExtraProperties plugin
[2023-04-28 13:48:28,000] INFO - Creating SimHub.Plugins.AudioControl.AudioControlPlugin plugin
[2023-04-28 13:48:28,016] INFO - Creating SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.InputPlugins.JoystickPlugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.InputPlugins.KeyboardReaderPlugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.Devices.DevicesPlugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
[2023-04-28 13:48:28,031] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
[2023-04-28 13:48:28,047] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
[2023-04-28 13:48:28,047] INFO - Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
[2023-04-28 13:48:28,047] INFO - Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2023-04-28 13:48:28,328] INFO - Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2023-04-28 13:48:28,360] INFO - Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2023-04-28 13:48:28,366] INFO - Initialising RSC.iRacingExtraProperties.IRacingExtraProperties plugin
[2023-04-28 13:48:28,380] INFO - Starting plugin : RSC - iRacing Extra Properties 2.2.3
[2023-04-28 13:48:28,860] INFO - Initialising SimHub.Plugins.AudioControl.AudioControlPlugin plugin
[2023-04-28 13:48:28,860] INFO - Initialising SimHub.Plugins.Devices.DevicesPlugin plugin
[2023-04-28 13:48:28,969] INFO - Initialising SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin
[2023-04-28 13:48:29,110] INFO - Initialising SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin
[2023-04-28 13:48:29,141] INFO - Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
[2023-04-28 13:48:29,563] INFO - Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
[2023-04-28 13:48:29,594] INFO - Initialising SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
[2023-04-28 13:48:29,594] INFO - Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2023-04-28 13:48:29,610] INFO - Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2023-04-28 13:48:29,610] INFO - Initialising SimHub.Plugins.InputPlugins.JoystickPlugin plugin
[2023-04-28 13:48:29,626] INFO - Initialising SimHub.Plugins.InputPlugins.KeyboardReaderPlugin plugin
[2023-04-28 13:48:29,626] INFO - Initialising SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
[2023-04-28 13:48:29,657] INFO - Initialising SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
[2023-04-28 13:48:30,532] INFO - Initialising SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
[2023-04-28 13:48:30,829] INFO - Starting Arduino in Multiple USB mode, devices configured :
	{"Rotation":2,"deviceName":"MAX7219+PWM fan","deviceUniqueId":"6f7785d5-8640-4b8e-819d-55b0279d3daa","displayModules":2,"readButtons":true,"disabled":false,"RgbLeds":0,"TargetRGBMatrix":1,"Motors":0,"speedLevel":11,"LCDRefreshSpeed":0}
	{"Rotation":0,"deviceName":"L298N Motor Rumble","deviceUniqueId":"ac337673-5be4-49ff-bee4-4c32d6bb82e1","displayModules":0,"readButtons":true,"disabled":false,"RgbLeds":0,"TargetRGBMatrix":1,"Motors":2,"speedLevel":11,"LCDRefreshSpeed":0}
[2023-04-28 13:48:30,844] INFO - Initialising SimHub.Plugins.Web.WebPlugin plugin
[2023-04-28 13:48:31,016] INFO - Web plugin suggested IP :192.168.1.112
[2023-04-28 13:48:31,032] INFO - Web plugin listening to 8888 (User friendly port)
[2023-04-28 13:48:31,079] INFO - Plugin manager correctly initialised
[2023-04-28 13:48:31,079] INFO - Loading plugins controls
[2023-04-28 13:48:31,980] INFO - Game successfully loaded
[2023-04-28 13:48:32,205] INFO - Allocating FMOD output for Speakers (Realtek High Definition Audio)
[2023-04-28 13:49:02,765] INFO - Disposing FMOD output for Speakers (Realtek High Definition Audio)
[2023-04-28 13:49:15,902] INFO - Installing package SimHub.ArduinoIDE.
[2023-04-28 13:49:15,930] INFO - Package SimHub.ArduinoIDE : starting download.
[2023-04-28 13:49:15,958] INFO - Package SimHub.ArduinoIDE : decompressing C:\Program Files (x86)\SimHub\Packages\SimHub.ArduinoIDE.1.0.0.7z into C:\Program Files (x86)\SimHub\_Addons\Arduino\ArduinoIDE
[2023-04-28 13:49:16,012] ERROR - Package SimHub.ArduinoIDE : error during installation : System.InvalidOperationException: nextHeaderOffset is invalid
   at SharpCompress.Common.SevenZip.ArchiveReader.ReadDatabase(IPasswordProvider pass)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.LoadFactory(Stream stream)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.LoadEntries(IEnumerable`1 volumes)
   at SharpCompress.Archives.AbstractArchive`2..ctor(ArchiveType type, SourceStream srcStream)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.Open(FileInfo fileInfo, ReaderOptions readerOptions)
   at SharpCompress.Factories.SevenZipFactory.Open(FileInfo fileInfo, ReaderOptions readerOptions)
   at SharpCompress.Archives.ArchiveFactory.Open(FileInfo fileInfo, ReaderOptions options)
   at SimHub.PackageManager.SimHubPackageManager.<Decompress>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.PackageManager.SimHubPackageManager.<Install>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.PackageManager.SimHubPackageManager.<Install>d__19.MoveNext().
[2023-04-28 13:49:16,019] ERROR - Unhandled dispatcher errorSystem.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\SimHub\Packages\SimHub.ArduinoIDE.1.0.0.7z' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at SimHub.PackageManager.SimHubPackageManager.DeleteIfExists(Boolean force, String downloadName)
   at SimHub.PackageManager.SimHubPackageManager.<Install>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.PackageManager.SimHubPackageManager.<Install>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.Plugins.OutputPlugins.Dash.WPFUI.Modules.ArduinoUploadInfoBanner.<arduinoSetup_Click>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SHWotever** [comment]
Hi ! Apparently the download got corrupted, are you using any proxy/vpn/accelerator services which could be caching a corrupted file ? 

I shared you all the files over GDrive here: https://drive.google.com/drive/folders/1-4zaAo5bxFdkop6HcBP13zphGbBCn9Bs?usp=sharing hopefully it would avoid the corrupted cache.

- Close simhub, 
- Download SimHub.ArduinoIDE.1.0.0.7z from https://drive.google.com/drive/folders/1-4zaAo5bxFdkop6HcBP13zphGbBCn9Bs?usp=sharing 
- Copy the file into C:\Program Files (x86)\SimHub_Addons\Arduino\ArduinoIDE (make sure not to rename the file)
- Start simhub and try to start again the setup tool

Nicolas

**Comment by westang78** [comment]
You're right. the compressed file was corrupted, it must have been cancelled or something when I first updated to SimHub 3.8.4, i didn't download from your GDrive, but instead I delete the corrupted file and let the SimHub re-download new one... and it works fine now. Thanks for the help.
