### ISSUE TITLE
Dash_1 ne se charge pas

### ISSUE THREAD

**Issue by herve4545** [SHWotever/SimHub#1293]
**Describe the bug**
Quand je quitte un jeu et que je veux charger le dash_1 ; ce dernier ne se charge pas. J'ai simplement une fenêtre blanche sans aucune indication
Si je veux charger le dash_2, il se charge sans problème

Ce problème se produit systématiquement avec rfactor 2
Je ne vois pas d'anomalie dans la log

**Simhub version**
Make sure to run the latest version

**To Reproduce**
1. Lancer rfactor 2 
2. Quitter le jeu
3. Charger le dash_1 et constater que la fenêtre est blanche 
4. Charger le dash_2 et constater qu'il se charge correctement

[dash.zip](https://github.com/SHWotever/SimHub/files/11355055/dash.zip)

**Comment by herve4545** [comment]
je réactive car ca apparait à nouveau
en sortie de rf2 semble être le cas le plus problématique

**Comment by SHWotever** [comment]
Hello! Est ce que tu as un peu plus de détails sur la configuration système/jeu ? Full screen, vsync ,gsync utilisation du chips et graphique du cpu (egpu) ? J'ai essayé sur deux pc ce weekend, en essayant un peu tout sans pouvoir le reproduire. A froid j'aurais tendance à penser que c'est l'utilisation du egpu qui peut être chafouin (souvent il s'agit d'Intel graphics dont les drivers sont "mehh"), ça peut aussi être simplement un manque de mémoire graphique (qui se configure dans le bios pour le egpu)

**Comment by SHWotever** [comment]
Est ce qui serait possible de retester en activant le mode debug ? Ça permet de logger des problèmes qui ne seraient pas liés directement à simhub.

**Comment by herve4545** [comment]
Core i5-12600k 
32 Go
Je n'utilise pas la puce graphique interne
NVIDIA 3080FE 10 Go
pas d'utilisation de vsync
J'utilise gsync sur mon 49" Samsung G9 en plein écran

Pendant le jeu, 
j'utilise 3 dash. 1 dash sur vocore+Arduino (onesimpro) et 2 dash en wifi sur tablette Android
J'utilise aussi shakeit motor avec un moteur+Arduino sur la pédale de frein
J'utilise aussi 12 bass-shakers avec 6 amplis nobsound

Ça fait plusieurs mois que j'ai ce probleme

Mode début 
OK. Je testerai jeudi car absent demain

**Comment by herve4545** [comment]
Hello
Mon test avec debug

1) je lance simhub
2) je lance rf2 et je quite rf2
3) dash_1 s'ouvre bien
4) je lance rf2 et je quite rf2
5) dash_1 s'ouvre bien
6) je lance rf2 et je quite rf2
7) dash_1 ne s'ouvre pas
8) dash_2 s'ouvre bien
9) dash_1 ne s'ouvre pas


j'ai oublié de préciser que je n'ai pas mis dans le fichier zip le contenu des "logos cars" et "splahs screen" qui se trouve dans ce dossier
\Software\SimHub\ImageLibrary\Herve45

je ne sais pas si ca peut jouer
dans tous les cas, ils sont disponible sur RD
https://www.racedepartment.com/downloads/herve_dash.39375/

[SimHub.zip](https://github.com/SHWotever/SimHub/files/11379924/SimHub.zip)

j'ai des erreurs avec crewchief. Je n'utilise pas ce soft

[2023-05-03 08:12:44,939] ERROR - First chance exception error RfactorReader.GameDataReadException: Exception of type 'RfactorReader.GameDataReadException' was thrown.
   at CrewChiefV4.rFactor2_V2.RF2SharedMemoryReader.ReadGameData(Boolean forSpotter)
Stacktrace :    at SimHubWPF.ErrorManagers.CurrentDomain_FirstChanceException(Object sender, FirstChanceExceptionEventArgs e)
   at CrewChiefV4.rFactor2_V2.RF2SharedMemoryReader.ReadGameData(Boolean forSpotter)
   at RfactorReader.RF2Manager.IsGameRunning()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
   at GameReaderCommon.GameLoop.MainLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by SHWotever** [comment]
Hello ! IsGameRunnin est normal, malheusement pas moyen de savoir si la télémétrie est active sans quelques erreurs.

Pour l'affichage, c'est dans le designer ? Je vois quelques traces de rendu du designer à la fin du log ?

**Comment by herve4545** [comment]
Oui je fais OPEN sur le dash et je n'ai qu'un fond d'écran blanc

**Comment by herve4545** [comment]
j'ai peut-être trouvé un élément intéressant
mon ecran principal est un 49"
simhub est lancé sur un écran secondaire 26". Le fenêtre principale est donc sur cet écran

aujourd'hui j'ai reproduit le cas ou ù mon dash_1 ne s'ouvre pas
la fenêtre de dash studio designer se lance sur mon écran principal (le 49") et c'est normal
la fenêtre de dash studio designer était toute blanche et je ne voyais donc pas le contenur de mon dash
j'ai attendu une trentaine de secondes et le dash ne s'est toujours pas affiché
j'ai alors déplacé la fenêtre principale de simhub (qui se trouve toujours sur mon 26") vers le 49" et le dash s'est affiché sur dash studio designer

quand tu m'as dit que tu voyais quelques trace de rendu designer, ca m'a interpellé

il faut savoir que j'ai displayMagician qui tourne en tâche de fond car il me permet de lancer des jeux en automatique vers une 3eme ecran (34")

peut-être que displaymagician est le perturbateur

je n'avais pas activé le débug cette fois-ci. Je n'ai donc pas de trace

....
je viens de le reproduire à l'instant à l'identique de ce qui est décrit ci-dessus avec la log
[SimHub.log](https://github.com/SHWotever/SimHub/files/11398503/SimHub.log)

**Comment by herve4545** [comment]
j'ai refait un 3eme test après avoir fermé displaymagician
ce dernier ne semble pas être en cause car le dash ne s'est pas affiché

j'ai à nouveau déplacé la fenêtre principale de simhub du 26" vers le 49" et le dash s'est affiché

ca serait donc un problème lié aux multi-ecrans

**Comment by SHWotever** [comment]
Hello ! 

J'ai regardé un peu dans tous les sens sans le reproduire pour l'instant. Dans la prochaine version j'ai mis à jour la vaste majorité des librairies utilisées dans l'affichage du designer. J'espère que ca airdera.

**Comment by herve4545** [comment]
Cool
Je suivrai l'affaire

**Comment by herve4545** [comment]
Problème résolu sur la beta v8.3.11b

**Comment by herve4545** [comment]
Résolu sur v8.3.11
