### ISSUE TITLE
Audio wont work for Shaker

### ISSUE THREAD

**Issue by moover00** [SHWotever/SimHub#1427]
I have been using Simhub for quite a while and suddenly a few weeks ago it stopped working.
Now the audio for the Shake it bass shakers wont connect?
I have followed all the instructions i could find online to try and rectify but no change.
I reinstalled the latest version and still the same.

The error log shows :
[2023-10-02 20:41:47,866] INFO - Disposing FMOD output for Speakers (2- USB Audio Device)
[2023-10-02 20:41:47,883] INFO - Allocating FMOD output for Speakers (2- USB Audio Device)
[2023-10-02 20:41:47,883] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2023-10-02 20:41:49,900] INFO - Disposing FMOD output for Speakers (2- USB Audio Device)
[2023-10-02 20:41:49,915] INFO - Allocating FMOD output for Speakers (2- USB Audio Device)
[2023-10-02 20:41:49,915] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2023-10-02 20:41:51,916] INFO - Disposing FMOD output for Speakers (2- USB Audio Device)
[2023-10-02 20:41:51,933] INFO - Allocating FMOD output for Speakers (2- USB Audio Device)
[2023-10-02 20:41:51,933] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()

Can you please offer some suggestions.

Regards

Ian

**Comment by SHWotever** [comment]
Hi ! 

There can be multiple causes to this :

- Drivers : bad/missing drivers installed, simhub uses waspi an advanced api for reducing latency even if windows can send a test sound it does not necessarily means waspai is working, uninstalling properly the driver and reinstalling it helps in such case.
- USB issues/power/bandwidth : I see that you are trying to use an usb sound card, it can be affected by cable/bandwidth/usb issues :
   - Try with another usb cable
   - Try to change the usb port (ideally remove any usb hub), if it's already connected to the motherboard try to move it away of any high bandwidth devices (webcams, mics etc ...)
   - Defective USB card, it sometimes happens, even more on cheap USB integrated amplifiers. This time testing the sound card with windows would give some clues
- Defective power transformer : in the case of an amp with integrated sound card, if the amp transformer is defective it can break usb communication as soon as the sound card gets initialized.
- Other devices bad driver : sometimes some audio soundcard/device (virtual sound card ...) comes with bad drivers and will affect other devices which were working previously, try to disable your sound cards one by one (run mmsys cpl and then you can right click on each one to disable it)
- Exclusive mode :  One of the most common issue, if you use some virtual mixers (IE Voicemeeter) software they can take the sound card in exclusive mode and prevent any direct connection. Make sure your sound card is free from any of these usages. you can also through mmsys.cpl disable exclusive mode :  in your device properties advanced statistics tab uncheck allow exclusive usage.
- Audio enhancements : once gain in mmsys.cpl, in your devices properties make sure that any enhancements are disabled.
- Inappropriate Default audio quality : once again through mmsys.cpl , in your device properties advanced statistics tab make sure the quality is set to 16bits 48000hz (DVD quality)

Let me know if it helped !
