### ISSUE TITLE
Vocore 5” lost connection 

### ISSUE THREAD

**Issue by Levis1234** [SHWotever/SimHub#1501]
My vocore  ( 5” inside a Gte pro PE wheel) loses the connection momentarily and reconnects by itself, thendashboard stops working for a second or two and works again , and keep doing this constantly at a random intervals

Everything other is working fine and i have tried all type of ports. In a hub , direct to pc in a 3.0 and 2.0

aleays same behaviour

here’s the log:

ERROR - SimHub.BitmapDisplay.Core.PipeServerBaseRemoteException: System.Exception: Vocore Communcation Error
   en SimHub.BitmapDisplay.Vocore.VOCOREService.Draw(DrawRequest drawRequest)
   at SimHub.BitmapDisplay.Core.PipeServerBase.WaitForResult[T](Func`1 action)
   at SimHub.BitmapDisplay.Core.PipeServerBase.InvokeWithParameters[T](Object parameters, String memberName)
   at SimHub.BitmapDisplay.Core.PipeBitmapDisplayServer.Draw(DrawRequest drawRequest)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.RemoteDisplayManagerBase`3.Draw()
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplay.VOCORE.RemoteVOCOREManager.SendBitmap(Byte[] bmp, Int32 width, Int32 height, Boolean flipDisplay)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplayBase.SendPicture()
[2023-12-24 17:35:37,905] INFO - Closing VOCORE remote USB display process
[2023-12-24 17:35:37,907] INFO - Web client disconnected : 127.0.0.1 AIM GS-DASH
[2023-12-24 17:35:38,116] INFO - Starting VOCORE remote USB display process
[2023-12-24 17:35:38,169] INFO - Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Scanning
[2023-12-24 17:35:38,251] INFO - Screen connected : model D500FPC931A-A 854x480, size 854x480, id 50-30-53-34-38-35-2D-30, leds 0

**Comment by SHWotever** [comment]
Hi ! From the log it's a connection loss. 

GSI made a complete guide about this available here : https://support.gomezsimindustries.com/portal/en/kb/articles/disconnects

In case this doesn't solve it does not hesitate to contact them directly so they can troubleshoot the hardware (cable, internals) : https://support.gomezsimindustries.com/portal/en/signin

**Comment by bmfair** [comment]
I have the same issue and have isolated it to a conflict with Simucube's Active Pedal "Tuner" software. Do you have an active pedal by chance? If not, then I'll open a new issue.

[2023-12-26 23:51:53,001] INFO - Starting VOCORE remote USB display process
[2023-12-26 23:51:53,009] INFO - Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Scanning
[2023-12-26 23:51:53,138] INFO - Screen connected : model D500FPC931A-A 854x480, size 854x480, id 39-00-CE-00-C5-FF-FF-FF, leds 0
[2023-12-26 23:51:53,212] INFO - VOCORE : Creating browser instance
[2023-12-26 23:51:53,226] INFO - VOCORE : Loading http://127.0.0.1:8888/Dash?v=3146#Lovely%20Dashboard|nocontrols|usbd480
[2023-12-26 23:51:53,243] INFO - Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Connected
[2023-12-26 23:51:53,319] INFO - Web client connected : 127.0.0.1, SimHubBrowser
[2023-12-26 23:51:53,360] INFO - Active dash on 127.0.0.1 : Lovely Dashboard
[2023-12-26 23:52:15,986] ERROR - SimHub.BitmapDisplay.Core.PipeServerBaseRemoteException: System.Exception: Vocore Communcation Error
   at SimHub.BitmapDisplay.Vocore.VOCOREService.Draw(DrawRequest drawRequest)
   at SimHub.BitmapDisplay.Core.PipeServerBase.WaitForResult[T](Func`1 action)
   at SimHub.BitmapDisplay.Core.PipeServerBase.InvokeWithParameters[T](Object parameters, String memberName)
   at SimHub.BitmapDisplay.Core.PipeBitmapDisplayServer.Draw(DrawRequest drawRequest)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.RemoteDisplayManagerBase`3.Draw()
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplay.VOCORE.RemoteVOCOREManager.SendBitmap(Byte[] bmp, Int32 width, Int32 height, Boolean flipDisplay)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplayBase.SendPicture()
[2023-12-26 23:52:15,988] INFO - Web client disconnected : 127.0.0.1 Lovely Dashboard
[2023-12-26 23:52:16,228] INFO - Closing VOCORE remote USB display process
[2023-12-26 23:52:18,242] INFO - Starting VOCORE remote USB display process

**Comment by Levis1234** [comment]
> Created Issue: #1502 (possibly related)
> 
> I have the same issue and have isolated it to a conflict with Simucube's Active Pedal "Tuner" software. Do you have an active pedal by chance?

No active pedal simucube for me, 
i have a simucube2 base . 

I havent solved all my disconnections,  but i have lograte to have less disconnections just plugging the usb directly to PC port 2.0  and putting a ferrite in the cable.

 Stil some disconnections and weird behaviour, but i will try with another cable to see what happen with better cable and keep looking

really seems a problem if EMI somewhere

**Comment by Vonger** [comment]
This has two possible reasons(also post to #1502)
1. USB cable is not good fit for high speed data transfer or nearby has strong EMI)
2. MPRO firmware is out of date, please upgrade to latest, here is tutorial: https://vonger.cn/?p=15453

**Comment by dan-the-man-nz** [comment]
Hi
i dont know if your screen is MPRO chip, but my 5" Vocore was completely unusable until yesterday when someone posted that above firmware update v0.15 in the discord, i had tried a half dozen diff cables, diff hubs, diff types of usb ports, ferrite chokes etc, spent more money on special cables and hubs than the screen cost, let alone so many wasted hours messing around with it

anything before v0.15 firmware the screen is hopeless in simhub
since v0.15 all disconnections are fixed its super stable

https://vonger.cn/misc/temp/mpro_upgrade.zip

**Comment by Levis1234** [comment]
After update the firmware yesterday ,no more error/lost connections for the moment

thanks to all and for the update on firmware

**Comment by SHWotever** [comment]
Thanks for the report !
