### ISSUE TITLE
Simcube Active Pedal Tuner Software Conflict with SimHub Vocore Communication Error

### ISSUE THREAD

**Issue by bmfair** [SHWotever/SimHub#1502]
**Describe the bug**
When Simucube's Active Pedal software "Simucube Tuner" is active (which it needs to be in order to provide the force feedback to the pedal), I get intermittent dropouts with SimHub's connection to Vocore.

**Simhub version**
9.1.19
Vocore 5" M-PRO
Simucube Tuner v1.13.2

**Third party plugins**
Only Arduino, Dash Studio, and Devices enabled. 
Fresh install with no third party plug-ins added. Using Lovely Dash, but issue happens with any (e.g. AudiConcept).

**To Reproduce**
1. Launch SimHub; dash works fine.
2. Launch Simucube Tuner, within seconds there will be communication errors with the Vocore.
4. End Simucube Tuner and the communication errors will stop (usually) - sometimes I have to reboot.

**Log files**
Join log files available in C:\Program Files (x86)\SimHub\Logs
Note : Bug reports not joining proper log files won't be processed (Never join logs screenshots/photos/extracts, please exclusively join complete logs files).

[2023-12-26 23:51:47,160] INFO - Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Scanning
[2023-12-26 23:51:47,178] INFO - Starting VOCORE remote USB display process
[2023-12-26 23:51:47,303] INFO - Screen connected : model D500FPC931A-A 854x480, size 854x480, id 39-00-CE-00-C5-FF-FF-FF, leds 0
[2023-12-26 23:51:47,347] INFO - VOCORE : Creating browser instance
[2023-12-26 23:51:47,360] INFO - VOCORE : Loading http://127.0.0.1:8888/Dash?v=3146#Lovely%20Dashboard|nocontrols|usbd480
[2023-12-26 23:51:47,376] INFO - Device Status changed : Generic Vocore Screen (4",4.3",5",6.8") : Connected
[2023-12-26 23:51:47,455] INFO - Web client connected : 127.0.0.1, SimHubBrowser
[2023-12-26 23:51:47,544] INFO - Active dash on 127.0.0.1 : Lovely Dashboard
[2023-12-26 23:51:50,773] ERROR - SimHub.BitmapDisplay.Core.PipeServerBaseRemoteException: System.Exception: Vocore Communcation Error
   at SimHub.BitmapDisplay.Vocore.VOCOREService.Draw(DrawRequest drawRequest)
   at SimHub.BitmapDisplay.Core.PipeServerBase.WaitForResult[T](Func`1 action)
   at SimHub.BitmapDisplay.Core.PipeServerBase.InvokeWithParameters[T](Object parameters, String memberName)
   at SimHub.BitmapDisplay.Core.PipeBitmapDisplayServer.Draw(DrawRequest drawRequest)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.RemoteDisplayManagerBase`3.Draw()
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplay.VOCORE.RemoteVOCOREManager.SendBitmap(Byte[] bmp, Int32 width, Int32 height, Boolean flipDisplay)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.BitmapDisplayBase.SendPicture()
[2023-12-26 23:51:50,778] INFO - Web client disconnected : 127.0.0.1 Lovely Dashboard
[2023-12-26 23:51:50,997] INFO - Closing VOCORE remote USB display process
[2023-12-26 23:51:53,001] INFO - Starting VOCORE remote USB display process

[SimHub.txt](https://github.com/SHWotever/SimHub/files/13776798/SimHub.txt)

**Other**
I've tried Vocore connected to various ports on the computer, no impact.

**Comment by SHWotever** [comment]
Hi ! This shows an usb connection drop. Seeing the log it's indeed coming regularly.

Considering the active pedals are probably using high speed servos : the fact of starting active tuner probably makes them "active" and starting to produce emi (interferences) .

To remove any clues of software conflicts (even if the log clearly shows to me an usb connection issue) I would try first with the pedals disconnected but the software running just to ensure it's not a software conflict (but I honestly really doubt it). 

To solve usb connection loss gsi made a very complete guide about it : https://support.gomezsimindustries.com/portal/en/kb/articles/disconnects

I would just add to this guide  that adding ferrite cores on both ends of  your screen usb cable (if the cable is good quality) can filter moderate emi 
![téléchargement](https://github.com/SHWotever/SimHub/assets/2207331/3af2b69b-086e-4198-9628-d999827e82f1) (in my personal case it solved issues with recently added motion with vocore screen)

**Comment by SHWotever** [comment]
Just an extra information: I see your are using an MPRO screen:
The manufacturer added some extra informations about issues in the first batchs of it : 
https://vonger.cn/?p=15464
https://vonger.cn/?p=15462

The first link mentions some mention high weaknesses about usb cables quality combined to emi (which the active pedals are likely to produce)

**Comment by bmfair** [comment]
Hi,
I have the Simucube pedals (and wheel) powered off (at the AC source - essentially unplugged). This is a video of the issue demonstrated: https://youtu.be/ZnVBBoIC5po

**Comment by bmfair** [comment]
Updated M-PRO firmware - no change:
Version: Nov 14 2023,00:40:10
Firmware Version: v0.14, 4

**Comment by bmfair** [comment]
Also, issue happens whether plugged into PC directly, or into USB hub. Normally I'm on Anker's USB 3.0 5A powered hub, and have a high quality USB 3.0 cable.

**Comment by SHWotever** [comment]
Thanks ! That's full of mystery, the log and your video clearly shows a connection loss (the half picture showing shifted is typical of it) I can't explain why the active tuner software would trigger it. Is it possible that usb is simply overloaded ? 

You mentioned turning off AC, but does the active pedals are still recognised in windows ? (which would mean there is still some usb activity). Usually redistributing usb connections (ideally straight from motherboard) can help. 

Can you confirm you are using an usb2.0 port for the screen as recommended ? https://github.com/SHWotever/SimHub/wiki/Dashstudio---USB-Displays#vocore-specific

Overall the MPRO version of vocore is pretty new and apparently there are still some issues with this model ([vonger.cn/?p=15464](https://vonger.cn/?p=15464) , do not hesitate to contact vocore support@vocore.io in case changing the usb cables/redistributing usb connections does not help.

**Comment by bmfair** [comment]
I've tried a variety of configurations now, none seem to make a difference:

- USB and power cables fully removed from Simucube devices, including the active pedal's USB to network hub
- USB2.0 powered hub 
- USB3.0 powered hub
- HP USB docking station 
- Direct attach to PC USB2 ports
- Direct attach to PC USB3 ports

All seem to result in disconnects that average about 1x / 10 seconds.

Eventually even exiting Simucube Tuner doesn't stop the problem, only a reboot.  However the problem only STARTS when the Simucube Tuner software is started.

**Comment by Vonger** [comment]
This has two possible reasons:
1. USB cable is not good fit for high speed data transfer.
2. MPRO firmware is out of date, please upgrade to latest, here is tutorial: https://vonger.cn/?p=15453

**Comment by bmfair** [comment]
Latest firmware posted today resolved, thanks Vonger!!!
