### ISSUE TITLE
Simagic Haptic Pedal does not show "Output Tuning" Menu 

### ISSUE THREAD

**Issue by xdtobi1993** [SHWotever/SimHub#1571]
**Describe the bug**
In the "ShakeIt Motors" Section the "Simagic P1000/P2000 Haptic Pedal Reactor" wont show any menu, when clicking "Output Tuning". It does not open any popup.
Usually you set the threshold and minimum force there.

**Simhub version**
every version starting at 9.2.0 has this bug

**To Reproduce**
1. Go to 'ShakeIt Motors'
2. Click on 'Motor Output'
3. Scroll down to 'Simagic P1000/P2000 Haptic Pedal Reactor'
4. Click on 'Output Tuning'
5. There is no popup opened

**Expected behavior**
A popup opens and you can edit the threshold and minimum force.

**Screenshots**
This how it looks in V9.2.10:
![image](https://github.com/SHWotever/SimHub/assets/153132957/c82d35d5-0eec-4365-a6af-3d0bae808e04)

**Log files**
[Logs.zip](https://github.com/SHWotever/SimHub/files/14641301/Logs.zip)
Error which is generated when clicking the button "Output Tuning":
[2024-03-18 20:11:44,643] ERROR - Unhandled dispatcher errorSystem.Windows.Markup.XamlParseException: Failed to create a 'Click' from the text 'SHButtonPrimary_Click'. ---> System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.
   at System.Delegate.CreateDelegate(Type type, Object target, String method, Boolean ignoreCase, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object target, String method)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateDelegateCritical(Type delegateType, Object target, String methodName)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateDelegate(Type delegateType, Object target, String methodName)
   at System.Xaml.EventConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value, XamlMember property)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateFromValue(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value, XamlMember property)
   at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String targetName, IAddLineInfo lineInfo)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at SimHub.Plugins.DataPlugins.ShakeItV3.UI.OutputSettings.Vibration.VibrationTuningSettings.InitializeComponent()
   at SimHub.Plugins.DataPlugins.ShakeItV3.UI.OutputSettings.Vibration.OutputSettingsButton.<SHButtonPrimary_Click>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SHWotever** [comment]
hi ! Thanks for the report it's already fixed for the next version : https://github.com/SHWotever/SimHub/issues/1564
