### ISSUE TITLE
Error downloading package SimHub.ArduinoIDE.1.0.0.7z

### ISSUE THREAD

**Issue by SolarGITM** [SHWotever/SimHub#1684]
**Describe the bug**
Following selecting the 'Open arduino setup tool' option the download dialogue progresses to 100% but then states unable to download / install the package with following error.

"Unable to download/install the package, please verify your internet access or firewall rules"

(During download file is being created in the packages directory but is deleted as the error dialogue appears).
(There is disk space for the file)

Tried without firewall
Tried running as administrator
Tried giving full access control to all Simhub directories
Tried running previous version (having completely removed all installed component's) with same result

**Simhub version**
9.04.4

**Third party plugins**
New install 

**To Reproduce**
1. Select Arduino from left menu bar
2. Select hardware from top menu
3. Select Open arduino setup tool
4. Wait for progress download to get to 100%
5. At 100% see error
6. Retry will just repeat the loop but cancel button is ignored when pressed - error dialogue has to be closed with mouse on corner cross

**Expected behavior**
Expected to see the Arduino dialogue.

**Screenshots**

**Log files**
[2024-09-07 14:18:10,422] INFO - Starting SimHub v9.4.4 (build time : 20/08/2024 17:43:27)
[2024-09-07 14:18:10,422] INFO - Windows Defender Controlled Folder Access : likely to be disabled
[2024-09-07 14:18:10,422] INFO - Administrator privileges : False 
[2024-09-07 14:18:10,422] INFO - OS version : Microsoft Windows NT 10.0.22631.0, Windows 10.0.22631
[2024-09-07 14:18:10,422] INFO - License status : Free
[2024-09-07 14:18:10,422] INFO - Process priority : Normal
[2024-09-07 14:18:10,428] INFO - Sound card changes notification registered
[2024-09-07 14:18:10,444] INFO - Searching for game readers
[2024-09-07 14:18:10,695] INFO - Scanning for additional game readers
[2024-09-07 14:18:12,337] INFO - 90 game readers loaded
[2024-09-07 14:18:12,619] INFO - (Re)Starting AssettoCorsa Game Manager and plugin manager
[2024-09-07 14:18:12,619] INFO - Creating Assetto Corsa game manager (ACSharedMemory.ACManager)
[2024-09-07 14:18:12,619] INFO - AssettoCorsa game manager created
[2024-09-07 14:18:12,619] INFO - Checking configuration status for AssettoCorsa
[2024-09-07 14:18:12,619] INFO - Detected install path : None
[2024-09-07 14:18:12,619] INFO - Configuration status for AssettoCorsa: GameNotDetected
[2024-09-07 14:18:12,619] INFO - Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, DevicesPlugin, KeyboardEmulatorPlugin, ShakeITBSV3Plugin, ShakeITMotorsV3Plugin, ShakeItWindPlugin, LapHitoryPlugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.Web.WebPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.AudioControl.AudioControlPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.InputPlugins.JoystickPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.Devices.DevicesPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
[2024-09-07 14:18:12,651] INFO - Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
[2024-09-07 14:18:12,664] INFO - Initializing SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2024-09-07 14:18:12,697] INFO - Initializing SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2024-09-07 14:18:12,713] INFO - Initializing SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2024-09-07 14:18:12,713] INFO - Initializing SimHub.Plugins.AudioControl.AudioControlPlugin plugin
[2024-09-07 14:18:12,713] INFO - Initializing SimHub.Plugins.Devices.DevicesPlugin plugin
[2024-09-07 14:18:12,791] INFO - Initializing SimHub.Plugins.DataPlugins.ShakeItWind.ShakeItWindPlugin plugin
[2024-09-07 14:18:12,791] INFO - Initializing SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
[2024-09-07 14:18:12,807] INFO - Initializing SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
[2024-09-07 14:18:12,807] INFO - Initializing SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
[2024-09-07 14:18:12,807] INFO - Initializing SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2024-09-07 14:18:12,807] INFO - Initializing SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2024-09-07 14:18:12,807] INFO - Initializing SimHub.Plugins.InputPlugins.JoystickPlugin plugin
[2024-09-07 14:18:12,807] INFO - Initializing SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
[2024-09-07 14:18:12,822] INFO - Initializing SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
[2024-09-07 14:18:12,978] INFO - Starting Arduino in Single USB mode
[2024-09-07 14:18:12,978] INFO - Initializing SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
[2024-09-07 14:18:13,088] INFO - Initializing SimHub.Plugins.Web.WebPlugin plugin
[2024-09-07 14:18:13,150] INFO - Web plugin listening to 8888 (User friendly port)
[2024-09-07 14:18:13,166] INFO - Web plugin suggested IP :192.168.0.31
[2024-09-07 14:18:13,213] INFO - Regenerating Web font-faces
[2024-09-07 14:18:13,291] INFO - Font-faces definitions extracted successfully
[2024-09-07 14:18:13,291] INFO - Font-faces updated successfully
[2024-09-07 14:18:13,322] INFO - Plugin manager correctly initialized
[2024-09-07 14:18:13,322] INFO - Loading plugins controls
[2024-09-07 14:18:13,354] INFO - JoystickManager : Found MOZA_CRP_pedals
[2024-09-07 14:18:13,495] INFO - Missing ports informations for : COM5
[2024-09-07 14:18:13,495] INFO - Missing ports informations for : COM6
[2024-09-07 14:18:13,509] INFO - Game successfully loaded
[2024-09-07 14:18:37,413] INFO - Hardware settings changed, restarting arduino controller(s)
[2024-09-07 14:18:37,413] INFO - Starting Arduino in Single USB mode
[2024-09-07 14:18:37,519] INFO - Missing ports informations for : COM5
[2024-09-07 14:18:37,519] INFO - Missing ports informations for : COM6
[2024-09-07 14:18:40,759] INFO - Installing package SimHub.ArduinoIDE.
[2024-09-07 14:18:40,779] INFO - Package SimHub.ArduinoIDE : starting download.
[2024-09-07 14:18:50,606] INFO - Arduino scan COM5, Unrecognised
[2024-09-07 14:18:50,663] INFO - Arduino scan COM6, Unrecognised
[2024-09-07 14:18:59,712] INFO - Arduino scan COM3, Unrecognised
[2024-09-07 14:18:59,739] INFO - Arduino scan COM7, Unrecognised
[2024-09-07 14:19:45,566] INFO - Package SimHub.ArduinoIDE : decompressing C:\Program Files (x86)\SimHub\Packages\SimHub.ArduinoIDE.1.0.0.7z into C:\Program Files (x86)\SimHub\_Addons\Arduino\ArduinoIDE
[2024-09-07 14:19:45,569] ERROR - Package SimHub.ArduinoIDE : error during installation : System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\SimHub\Packages\SimHub.ArduinoIDE.1.0.0.7z'.
File name: 'C:\Program Files (x86)\SimHub\Packages\SimHub.ArduinoIDE.1.0.0.7z'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at SharpCompress.Archives.ArchiveFactory.FindFactory[T](FileInfo finfo)
   at SharpCompress.Archives.ArchiveFactory.Open(FileInfo fileInfo, ReaderOptions options)
   at SimHub.PackageManager.SimHubPackageManager.<Decompress>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.PackageManager.SimHubPackageManager.<Install>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SimHub.PackageManager.SimHubPackageManager.<Install>d__19.MoveNext().

**Additional context**

**Comment by SHWotever** [comment]
Hi ! Can you check that your antivirus is not blocking it ? Seeing the logs it seems to download successfully the the downloaded file seems to "vanish".

As a workaround you can find a preinstalled version of the arduino here : https://simhubdash.com/Packages/ArduinoIDEPresinstalled.zip 
Simply download and decompress inside c:\Program Files (x86)\SimHub\ and accept any files to be overwritten. Once done simhub will recognize it as installed.

Best regards,
Nicolas

**Comment by SolarGITM** [comment]
Nicolas,

Fantastic thanks very much 

I had already inspected the firewall antivirus logs which show nothing blocked or quarantined (that I can see), very happy to look at any other specific settings it is just a standard windows 10 build with default firewall and antivirus rules.

The workaround worked 1st go so I am good to go.

Amazing software ! - many thanks again.
