### ISSUE TITLE
Missing dashboard

### ISSUE THREAD

**Issue by dusnake** [SHWotever/SimHub#450]
For several days it is impossible to see my dashboard. The option has stopped appearing on the menu. I have tried everything, reinstall in all the indicated ways, completely erase and reinstall, remove and put components, but nothing has worked. I'm in the last version

Attach error trace

[2019-12-01 21:55:16,175] ERROR - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Management.ManagementException: Espacio de nombres no válido 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementEventWatcher.Initialize()
   at System.Management.ManagementEventWatcher.Start()
   at WoteverCommon.USBChangeDetectorService.add_DevicesChanged(EventHandler value)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.PSE.PSELedsManager..ctor()
   at SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at SimHub.Plugins.PluginManager..ctor(IGameManager gameManager, IList`1 allowedUserPlugins)
[2019-12-01 21:55:16,929] ERROR - System.Management.ManagementException: Espacio de nombres no válido 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementEventWatcher.Initialize()
   at System.Management.ManagementEventWatcher.Start()
   at WoteverCommon.USBChangeDetectorService.add_DevicesChanged(EventHandler value)
   at SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersManager.Start()
   at SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin.Init(PluginManager pluginManager)
   at SimHub.Plugins.PluginManager..ctor(IGameManager gameManager, IList`1 allowedUserPlugins)
[2019-12-01 21:55:29,420] ERROR - System.Management.ManagementException: Espacio de nombres no válido 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementEventWatcher.Initialize()
   at System.Management.ManagementEventWatcher.Start()
   at WoteverCommon.(EventHandler value)
   at ACToolsUtilities.JoystickManagerSlimDX..ctor(Func`2 getStoredName, Action`2 setStoredName)
   at SimHub.Plugins.InputPlugins.JoystickPlugin.Init(PluginManager pluginManager)
   at SimHub.Plugins.PluginManager..ctor(IGameManager gameManager, IList`1 allowedUserPlugins)

**Comment by SHWotever** [comment]
Hi ! It looks like your WMI service is disabled (it's used to detect new plugged devices and avoid active polling in order to reduce CPU) Make sure to enable it and start it in windows services : 
![image](https://user-images.githubusercontent.com/2207331/69984085-8ca1fe80-1538-11ea-9985-c420e85194fc.png)

I think the service in spanish will be named "administración de Windows" but I'm not 100% sure.

When the service will be running properly the plugin will be able to start again.

Let me know if it helped, 
Best regards,

Nicolas

**Comment by dusnake** [comment]
The service you indicate is correct, as you put in the screenshot :(

**Comment by SHWotever** [comment]
Hum ! Weird, it means something is corrupted in windows, I added a workaround in Simhub to avoid using it when it's not available, the downside is that it will eat a bit more CPU compared to WMI when it's working. You can download the beta with the workaround here : https://www.simhubdash.com/unofficial/SimHub.6.09.2b2.zip

Ps :WMI is an important component in windows and if it's broken you will probably have issues with other software.

Let me know,
Nicolas

**Comment by dusnake** [comment]
Works perfect!!! awesome!! only have this error in log, but maybe is not important


  | ERROR | USBChangeDetectorService: Could not start WMI event watcher, switching to fallback mode (polling every 10s) System.Management.ManagementException: Espacio de nombres no válido    at System.Management.ThreadDispatch.Start()   at System.Management.ManagementScope.Initialize()   at System.Management.ManagementEventWatcher.Initialize()   at System.Management.ManagementEventWatcher.Start()   at WoteverCommon.USBChangeDetectorService.add_DevicesChanged(EventHandler value)
-- | -- | --

**Comment by SHWotever** [comment]
Nice ! Thanks for the feedback

Indeed it was expected. I obviously can't solve the WMI corruption you are encountering but when simhub detects it, it will switch to the fallback mode.

**Comment by dusnake** [comment]
i paste this link, maybe helps someone in the future with wmi

https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10

**Comment by SHWotever** [comment]
Thanks for the link, I will remember it if it happens to someone else !
