### ISSUE TITLE
System info - Error and missing provider list

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#458]
Hi again!
I have a reoccurring error related the CPU fan speed:

[2019-12-22 09:08:01,858] ERROR - Error while getting value of SystemInfosProvider.MainCPUFanSpeed
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at WoteverCommon.WPF.HybridSortedObservableCollection`1.GetValueOrDefault(String key)
   at SimHub.Plugins.DataPlugins.SystemInfosProviderSettingsItem.get_SelectedValue()
   at SimHub.Plugins.DataPlugins.SystemInfosProvider.<>c__DisplayClass11_0.<Init>b__5()
   at SimHub.Plugins.PluginManager.<>c__DisplayClass154_0`1.<AttachDelegate>b__0()
   at SimHub.Plugins.PluginManager.GetPropertyValue(String name)
[2019-12-22 09:08:01,869] ERROR - Unhandled dispatcher errorSystem.ArgumentNullException: Value cannot be null.

[SimHub.log.1.zip](https://github.com/SHWotever/SimHub/files/3992263/SimHub.log.1.zip)

Possibly related, prop values are missing in the available property screen (not all, and not always) : 
![image](https://user-images.githubusercontent.com/50543913/71319217-851ca800-249b-11ea-8a94-453d7f82dcfc.png)

Also this doesn't look right (but my system monitor dash seems to work fine): 
![image](https://user-images.githubusercontent.com/50543913/71319227-a2ea0d00-249b-11ea-918d-ed6d2b582070.png)

Bon dimanche!

**Comment by SHWotever** [comment]
Woopsi doopise, I indeed changed a few things for performances reasons, i've released an hotfix ;)

**Comment by Romainrob** [comment]
Thanks for the fast hotfix! :)
Bonne journée!
