### ISSUE TITLE
ACC - Error loop

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#466]
Hi.
I can't get SimHub to work with ACC.
As soon as the game is selected I get a loop of these : 

[2020-01-10 18:33:04,226] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at ACSharedMemory.ACCManager.CheckGameRunning()
   at ACSharedMemory.ACCManager.IsGameRunning()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
[2020-01-10 18:33:04,242] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at ACSharedMemory.ACCManager.CheckGameRunning()
   at ACSharedMemory.ACCManager.IsGameRunning()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)

[SimHub.zip](https://github.com/SHWotever/SimHub/files/4046879/SimHub.zip)

**Comment by Romainrob** [comment]
Actually the error loop stops once the game is loaded and doesn't come back when going back to the main menu.
So it's only happening when in the main menu, until I load the game once. Not that bad.

**Comment by SHWotever** [comment]
Hi ! Could I ask the full log ? I could not reproduce it yet, the full log may help me to understand what leads to this issue.

**Comment by Romainrob** [comment]
Sure.
[SimHub.zip](https://github.com/SHWotever/SimHub/files/4047905/SimHub.zip)
Everything worked fine after loading the game once.
But you can see the error loops while I'm in the menu before that.
Let me know if I can test anything to help.

**Comment by SHWotever** [comment]
Thanks ! I got it after a full computer reboot, looks like the shared memory was not freed by the game (even when not running anymore) which avoided the crash loop. I should reboot more than once a month :D

**Comment by Romainrob** [comment]
Did you turn it off and on again? :) But to break it this time

**Comment by ValokAsura** [comment]
I just thought I would mention that have the same error spam as Romainrob using 6.9.5. Eventually it stops after I load up the game. Until then it just slowly creates a larger and larger log file.

**Comment by Romainrob** [comment]
Hi. The error loop is gone on 6.9.6 on my end.
Thank you! :)

**Comment by SHWotever** [comment]
Thanks for the feedback ! Indeed I released the fix at the same time.
