### ISSUE TITLE
SimHub Sound Output Issue 

### ISSUE THREAD

**Issue by DrOrzy** [SHWotever/SimHub#499]
G'Day guys, i am a total noob when it come's to the technical side with PC's. Please see the log file i have copied and pasted below. I have been using SimHub faultlessly for over a year now for my Buttkicker however i noticed it not working a few days after i updated the BIOS on my pc.  Ryzen 2700x with Prime x470 pro board. Not sure if its just a coincidence or something else. However the RealTek Sound Output shows up with "Connection Error" in red within SimHub ShakIt Bass Shakers. This is the same for whichever output source i select. Headphone, speakers, all of them! Connection Error for everyone of them. Seems like SimHub is not outputting or able to talk to my soundcard at all. I have tried uninstalling and Reinstalling both RealTek HD and also SimHub with no result. Hopefully someone can help me resolve this issue. If there's anymore info needed, let me know. As i said , i'm  a total noob when it comes to this side of things.

Cheers, 
Orz

2020-03-02 12:09:15,139] INFO - Starting SimHub v6.9.7 (build time : 22/02/2020 20:50:39)
[2020-03-02 12:09:15,147] INFO - Administrator privileges : True 
[2020-03-02 12:09:15,151] INFO - OS version : Microsoft Windows NT 10.0.18363.0, Windows 10.0.18363
[2020-03-02 12:09:15,151] INFO - License status : Licensed
[2020-03-02 12:09:15,151] INFO - Process priority : Normal
[2020-03-02 12:09:16,878] INFO - (Re)Starting AssettoCorsaCompetizione Game Manager and plugin manager
[2020-03-02 12:09:16,881] INFO - Creating Assetto Corsa Competizione game manager (ACSharedMemory.ACCManager)
[2020-03-02 12:09:16,912] INFO - AssettoCorsaCompetizione game manager created
[2020-03-02 12:09:16,912] INFO - Setting listening UDP to 9000
[2020-03-02 12:09:16,926] INFO - Checking configuration status for AssettoCorsaCompetizione
[2020-03-02 12:09:16,933] INFO - Configuration status for AssettoCorsaCompetizione: GameConfigured
[2020-03-02 12:09:16,934] INFO - Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, GarySwallowDataPlugin, KeyboardEmulatorPlugin, NextionPlugin, PureAddictPlugin, ShakeITBSV3Plugin, ShakeITMotorsV3Plugin, LapHitoryPlugin, ThrustmastersPlugin
[2020-03-02 12:09:20,398] INFO - JoystickManager : Starting game controllers detection
[2020-03-02 12:09:20,505] INFO - JoystickManager : Found FANATEC_CSL_Elite_Wheel_Base_PlayStation_4
[2020-03-02 12:09:20,538] INFO - JoystickManager : Found FANATEC_CSL_Elite_Wheel_Base_PlayStation_4
[2020-03-02 12:09:20,550] INFO - JoystickManager : End of detection
[2020-03-02 12:09:20,774] INFO - Loading font list
[2020-03-02 12:09:21,640] INFO - Starting Arduino in Single USB mode
[2020-03-02 12:09:21,690] INFO - Matrix custom font custommatrixfont8x8 loaded
[2020-03-02 12:09:21,712] INFO - Font list loading successful
[2020-03-02 12:09:21,925] INFO - Web suggested IP :192.168.1.39
[2020-03-02 12:09:22,025] INFO - Web font-faces up to date
[2020-03-02 12:09:22,026] INFO - Loading plugins controls
[2020-03-02 12:09:23,292] INFO - Game successfully loaded
[2020-03-02 12:09:24,442] INFO - USBD480 : Found 0 display(s)
[2020-03-02 12:10:45,057] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:45,162] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:10:47,171] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:47,187] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:47,190] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:10:49,202] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:49,222] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:49,225] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:10:51,236] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:51,254] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:51,257] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:10:53,270] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:53,288] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:53,291] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:10:55,304] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:55,321] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:55,324] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:10:57,337] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:57,354] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:57,357] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:10:59,371] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:59,387] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:10:59,390] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:01,403] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:01,421] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:01,424] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:03,437] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:03,454] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:03,457] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:05,469] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:05,488] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:05,491] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:07,504] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:07,520] INFO - Allocating FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:07,523] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:07,872] INFO - Disposing FMOD output for Realtek Digital Output (Realtek High Definition Audio)
[2020-03-02 12:11:08,670] INFO - Allocating FMOD output for Headphones (2- Arctis 7 Game)
[2020-03-02 12:11:08,674] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:10,687] INFO - Disposing FMOD output for Headphones (2- Arctis 7 Game)
[2020-03-02 12:11:10,705] INFO - Allocating FMOD output for Headphones (2- Arctis 7 Game)
[2020-03-02 12:11:10,708] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:12,720] INFO - Disposing FMOD output for Headphones (2- Arctis 7 Game)
[2020-03-02 12:11:12,737] INFO - Allocating FMOD output for Headphones (2- Arctis 7 Game)
[2020-03-02 12:11:12,741] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:13,639] INFO - Disposing FMOD output for Headphones (2- Arctis 7 Game)
[2020-03-02 12:11:15,285] INFO - Allocating FMOD output for Speakers Main (NVIDIA High Definition Audio)
[2020-03-02 12:11:15,288] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:17,304] INFO - Disposing FMOD output for Speakers Main (NVIDIA High Definition Audio)
[2020-03-02 12:11:17,320] INFO - Allocating FMOD output for Speakers Main (NVIDIA High Definition Audio)
[2020-03-02 12:11:17,323] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:18,621] INFO - Disposing FMOD output for Speakers Main (NVIDIA High Definition Audio)
[2020-03-02 12:11:19,870] INFO - Allocating FMOD output for MySoundSource (NVIDIA High Definition Audio)
[2020-03-02 12:11:19,873] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:21,886] INFO - Disposing FMOD output for MySoundSource (NVIDIA High Definition Audio)
[2020-03-02 12:11:21,904] INFO - Allocating FMOD output for MySoundSource (NVIDIA High Definition Audio)
[2020-03-02 12:11:21,907] ERROR - Can't connect to output System.Exception: ERR_OUTPUT_INIT
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Check(RESULT res)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.FindDriver(String deviceId, Int32& systemRate, Int32& channels)
   at SimHub.Plugins.DataPlugins.ShakeItV3.Settings.Audio.Core.FModOutput.Configure()
[2020-03-02 12:11:21,937] INFO - Disposing FMOD output for MySoundSource (NVIDIA High Definition Audio)
[2020-03-02 12:14:20,682] INFO - Application exit
[2020-03-02 12:14:20,737] INFO - Stopping game manager
[2020-03-02 12:14:20,742] INFO - Stopping plugin manager
[2020-03-02 12:14:20,744] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
[2020-03-02 12:14:20,745] INFO - SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin settings saved
[2020-03-02 12:14:20,745] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.SystemInfosProvider
[2020-03-02 12:14:20,746] INFO - SimHub.Plugins.DataPlugins.SystemInfosProvider plugin settings saved
[2020-03-02 12:14:20,746] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2020-03-02 12:14:20,782] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin settings saved
[2020-03-02 12:14:20,782] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2020-03-02 12:14:20,787] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin settings saved
[2020-03-02 12:14:20,787] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin
[2020-03-02 12:14:20,806] INFO - SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin plugin settings saved
[2020-03-02 12:14:20,806] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2020-03-02 12:14:20,814] INFO - SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin settings saved
[2020-03-02 12:14:20,814] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin
[2020-03-02 12:14:20,826] INFO - SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin settings saved
[2020-03-02 12:14:20,826] INFO - Stopping plugin SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
[2020-03-02 12:14:20,826] INFO - Stopping plugin SimHub.Plugins.DataPlugins.SystemInfosProvider
[2020-03-02 12:14:20,826] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin
[2020-03-02 12:14:20,839] INFO - Stopping plugin GarySwallow.PluginSdk.GarySwallowDataPlugin
[2020-03-02 12:14:20,840] INFO - Stopping plugin User.PluginSdkDemo.PureAddictPlugin
[2020-03-02 12:14:20,841] INFO - Stopping plugin SimHub.Plugins.AudioControl.AudioControlPlugin
[2020-03-02 12:14:20,879] INFO - Stopping plugin SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin
[2020-03-02 12:14:20,881] INFO - Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2020-03-02 12:14:20,881] INFO - Finalizing plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2020-03-02 12:14:20,881] INFO - Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2020-03-02 12:14:20,881] INFO - Finalizing plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2020-03-02 12:14:20,881] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin
[2020-03-02 12:14:20,881] INFO - Stopping plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin
[2020-03-02 12:14:20,881] INFO - Finalizing plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin
[2020-03-02 12:14:20,881] INFO - Stopping plugin SimHub.Plugins.InputPlugins.JoystickPlugin
[2020-03-02 12:14:20,882] INFO - Stopping plugin SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin
[2020-03-02 12:14:20,882] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin
[2020-03-02 12:14:20,886] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2020-03-02 12:14:20,887] INFO - Finalizing plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2020-03-02 12:14:20,888] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin
[2020-03-02 12:14:20,908] INFO - Stopping plugin SimHub.Plugins.Web.WebPlugin
[2020-03-02 12:14:20,909] INFO - Finalizing plugin SimHub.Plugins.Web.WebPlugin
[2020-03-02 12:14:20,909] INFO - Stopped all plugins
[2020-03-02 12:14:20,909] INFO - Performance dump
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin::DataUpdate	17760calls	190ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin::DataUpdate	17760calls	1ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - User.PluginSdkDemo.PureAddictPlugin::DataUpdate	17760calls	0ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin::DataUpdate	17760calls	18ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.AudioControl.AudioControlPlugin::DataUpdate	17760calls	1ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - GarySwallow.PluginSdk.GarySwallowDataPlugin::DataUpdate	17760calls	61296ms	17760calls	3.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin::DataUpdate	17760calls	32ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - JoystickPlugin::PollThread	14318calls	30ms	14318calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin::DataUpdate	17760calls	0ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin::DataUpdate	17760calls	0ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin::DataUpdate	17760calls	960ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin::DataUpdate	17760calls	0ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.Web.WebPlugin::DataUpdate	17760calls	92ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin::DataUpdate	17760calls	3ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,909] INFO - JoystickManager::DetectJoysticks	1calls	277ms	1calls	277.000ms/call
[2020-03-02 12:14:20,910] INFO - SimHub.Plugins.DataPlugins.SystemInfosProvider::DataUpdate	17760calls	0ms	17760calls	0.000ms/call
[2020-03-02 12:14:20,910] INFO - Final Exit

**Comment by SHWotever** [comment]
Hi ! 
Indeed the logs shows that Fmod can't access any of your sound cards, I can't see anything ouside of that so I feel it could be something system wide, I've already seen some issues with advanded mixing softwares like "apo". Are you using something like that (Or similar) ? 

Nicolas

**Comment by DrOrzy** [comment]
Thankyou for getting back to me.

No, I’m not using anything else for advanced audio mixing. The strange
thing is that my soundcard is working as it should with everything else.
ie, the sims I’m running, my external microphone, headphones, external
speakers through my sound system all is fine. Which is why my initial
thought was to just uninstall SimHub and reinstall it hoping that would
resolve the issue. When that didn’t fix it I thought maybe there was an
update or some setting that I may have inadvertently switched off or not On
within SimHub.

Kind Regards,
Orz.

**Comment by DrOrzy** [comment]
Ok, I think I have resolved the issue. 

Not sure why uninstalling and reinstalling the Realtek drivers didn’t work initially. 

I went to the Asus downloads page, downloaded and reinstalled the audio drivers for my Motherboard (Prime x470 Pro) and voilá, Issue resolved!!! SimHub and buttkicker is working again as it should be 😁 Bloody computers 🤯🤯

**Comment by SHWotever** [comment]
Nice ! Thanks a lot for the feedback !
Have fun !
