### ISSUE TITLE
SimHub is frozen.

### ISSUE THREAD

**Issue by Geoffski74** [SHWotever/SimHub#508]
When I boot up the program, it loads the interface but does not load any games. nothing is able to be controlled and I have to use task manager to close it down. Because of this I cant get a log from the program but here is the latest one from my program files.. The log I don't think shows the issue.

[2020-03-17 19:48:38,948] INFO - Starting SimHub v6.9.7 (build time : 22/02/2020 09:50:39)
[2020-03-17 19:48:38,957] INFO - Administrator privileges : True 
[2020-03-17 19:48:38,962] INFO - OS version : Microsoft Windows NT 10.0.18362.0, Windows 10.0.18362
[2020-03-17 19:48:38,962] INFO - License status : Free
[2020-03-17 19:48:38,962] INFO - Process priority : Normal
[2020-03-17 19:48:53,617] INFO - (Re)Starting PCars2 Game Manager and plugin manager
[2020-03-17 19:48:53,620] INFO - Creating Project Cars 2 game manager (PCarsSharedMemory.PC2.PCars2Manager)
[2020-03-17 19:48:53,639] INFO - PCars2 game manager created
[2020-03-17 19:48:53,642] INFO - Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, KeyboardEmulatorPlugin, NextionPlugin, LapHitoryPlugin
[2020-03-17 19:48:54,933] INFO - JoystickManager : Starting game controllers detection
[2020-03-17 19:48:54,968] INFO - JoystickManager : Found FANATEC_CSL_Elite_Pedals_LC
[2020-03-17 19:48:54,978] INFO - JoystickManager : Found Aiologs_SQ_Shifter
[2020-03-17 19:48:54,978] INFO - JoystickManager : Found T500_RS_Gear_Shift
[2020-03-17 19:48:54,979] INFO - JoystickManager : Found Aiologs_Handbrake
[2020-03-17 19:48:54,980] INFO - JoystickManager : End of detection
[2020-03-17 19:48:55,077] INFO - Loading font list
[2020-03-17 19:48:55,407] INFO - Starting Arduino in Single USB mode
[2020-03-17 19:48:55,431] INFO - Matrix custom font custommatrixfont8x8 loaded
[2020-03-17 19:48:55,498] INFO - Font list loading successful
[2020-03-17 19:48:55,571] INFO - Web suggested IP :192.168.0.12
[2020-03-17 19:48:55,620] INFO - Web font-faces up to date
[2020-03-17 19:48:55,622] INFO - Loading plugins controls
[2020-03-17 19:48:55,846] ERROR - Error while loading game manager
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SimHub.Plugins.DataPlugins.PersistantTracker.DBManager.<>c__DisplayClass14_0.<GetLaps>b__0(LiteDatabase GameStore)
   at SimHub.Plugins.PluginManager.WithGameDatabase[T](Func`2 callback, LiteDatabase container)
   at SimHub.Plugins.DataPlugins.PersistantTracker.DBManager.GetLaps(Guid sessionId, LiteDatabase container)
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel.<>c__DisplayClass7_0.<RefreshSessions>b__1(SessionRecord i)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel.<RefreshSessions>b__7_0(LiteDatabase gameStore)
   at SimHub.Plugins.PluginManager.WithGameDatabase(Action`1 callback, LiteDatabase container)
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel.RefreshSessions()
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel..ctor(DBManager dBmanager)
   at SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin.GetWPFSettingsControl(PluginManager pluginManager)
   at SimHubWPF.MainWindow.LoadPluginsControls()
   at SimHubWPF.MainWindow.<>c__DisplayClass35_0.<ChangeGame>b__3()
[2020-03-17 19:48:55,866] ERROR - Error while loading game manager
System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.DataPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.<Find>d__9.MoveNext()
   at LiteDB.LiteEngine.<Find>d__13.MoveNext()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SimHub.Plugins.DataPlugins.PersistantTracker.DBManager.<>c__DisplayClass14_0.<GetLaps>b__0(LiteDatabase GameStore)
   at SimHub.Plugins.PluginManager.WithGameDatabase[T](Func`2 callback, LiteDatabase container)
   at SimHub.Plugins.DataPlugins.PersistantTracker.DBManager.GetLaps(Guid sessionId, LiteDatabase container)
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel.<>c__DisplayClass7_0.<RefreshSessions>b__1(SessionRecord i)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.ObjectModel.ObservableCollection`1.CopyFrom(IEnumerable`1 collection)
   at System.Collections.ObjectModel.ObservableCollection`1..ctor(IEnumerable`1 collection)
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel.<RefreshSessions>b__7_0(LiteDatabase gameStore)
   at SimHub.Plugins.PluginManager.WithGameDatabase(Action`1 callback, LiteDatabase container)
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel.RefreshSessions()
   at SimHub.Plugins.DataPlugins.PersistantTracker.HistoryModel..ctor(DBManager dBmanager)
   at SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin.GetWPFSettingsControl(PluginManager pluginManager)
   at SimHubWPF.MainWindow.LoadPluginsControls()
   at SimHubWPF.MainWindow.<>c__DisplayClass35_0.<ChangeGame>b__3()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.DispatcherOperation.Wait()
   at SimHubWPF.MainWindow.ChangeGame(SupportedGameManager game)
[2020-03-17 19:49:00,323] INFO - Found one device on COM3 named {
  "ConnectedModel": "j",
  "Features": "GNJPXV",
  "TM1638ModulesCount": 0,
  "UniqueId": null,
  "DeviceName": "WINDSIM",
  "MotorsCount": 4,
  "PortName": "COM3",
  "HasBoost": 0,
  "HasSpeedo": 0,
  "IsBluetooth": false,
  "HasTacho": 0,
  "HasI2CLcd": false,
  "HasRGBMatrix": false,
  "ExpandedFeatures": [
    "mcutype",
    "Gear",
    "Motors"
  ],
  "MotorsBoard": "Adafruit Motor Shield V2",
  "MaxAheadDatagrams": 0,
  "DatagramMaxLength": 0,
  "MCUModel": "ATmega328P",
  "ReceivedDatagramsCount": 0
}
[2020-03-17 19:49:00,324] INFO - Switching device named WINDSIM to speed level 11 on COM3
[2020-03-17 19:49:00,324] INFO - Switching device on port COM3 to speed level 11, 115200 bauds
[2020-03-17 19:49:00,836] INFO - Connected to device on COM3 named WINDSIM

**Comment by SHWotever** [comment]
Hi ! It looks like the lap database is corrupted could you delete the following file : C:\Program Files (x86)\SimHub\PluginsData\PCars2\DataStore.db it will reset it and everything should be working again,

Let me know,
Nicolas

**Comment by Geoffski74** [comment]
Thank you very much.. Yea that fixed the problem.. 
Really appreciate your help...

**Comment by SHWotever** [comment]
Thanks for the feedback ! Have fun !
