### ISSUE TITLE
GetParticipantIndex() out of bounds AMS2

### ISSUE THREAD

**Issue by Wergilius** [SHWotever/SimHub#551]
Sometimes (not always) I get this error when I start AMS2

[2020-05-02 21:03:07,384] INFO - Game connected
[2020-05-02 21:03:07,384] ERROR - System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PCarsSharedMemory.PC2.PCars2Manager.GetParticipantIndex()
   at PCarsSharedMemory.PC2.PCars2Manager.GD_CompletedLaps()
   at GameReaderCommon.GameManagerBase`3.PreParseDataBase()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
[2020-05-02 21:03:07,413] INFO - All time best found : 00:01:55.2930000 recorded at 5/2/2020 8:20:13 PM
[2020-05-02 21:06:07,203] ERROR ....

And what I assume, errors following the first error

**Comment by SHWotever** [comment]
Hi ! I could not reproduce it, but i've added an additional security to avoid the error for the next version.
