### ISSUE TITLE
ERROR - An error occured

### ISSUE THREAD

**Issue by Jxffries** [SHWotever/SimHub#584]
Hi,

I use an iPad with SimHub and the Philm dashboard 
( https://www.racedepartment.com/downloads/simhub-custom-dashboards.20460/ )

Every now and again the app will just take me back to the dashboard menu during driving. I've attached the log below.
Thank you.

EDIT: This is the line of code when the 'crash' appears.

[2020-05-24 18:14:00,110] ERROR - An error occured while executing binding on FuelValue System.FormatException: Token is not valid.
   at MS.Internal.Parsers.ParseColor(String color, IFormatProvider formatProvider, ITypeDescriptorContext context)
   at System.Windows.Media.ColorConverter.ConvertFromString(String value)
   at SimHub.Plugins.OutputPlugins.GraphicalDash.EditorModel.Applybindings(IBindable item, String objectName, DashboardBindingData binding, IFormulaEngine GraphicalDashEngine), formula will not be evaluated for 30s

[SimHub.log](https://github.com/SHWotever/SimHub/files/4674051/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! 
Thanks for the log ! The error is not a technical error and has no impact on the web device.
I see that your device is still running ios 9 can you update it to ios 10 or more ? Unfortunately safari on ios 9 has some memory leaks which has been fixed later by Apple.
