### ISSUE TITLE
Audio crash had to force quit.

### ISSUE THREAD

**Issue by gptech2444** [SHWotever/SimHub#673]
Playing iracing and using universal simhub dash. 
Audio got stuck in a loop and had to force quit simhub.
[2020-10-05 21:45:06,243] ERROR - Error while playing Mp3 : NAudio.MmException: MemoryAllocationError calling waveOutWrite
   at NAudio.Wave.WaveOutBuffer.WriteToWaveOut()
   at NAudio.Wave.WaveOutBuffer.OnDone()
   at NAudio.Wave.WaveOut.EnqueueBuffers()
   at NAudio.Wave.WaveOut.Play()
   at SimHub.Plugins.AudioControl.AudioPlayPlugin.<>c__DisplayClass7_0.<Play>b__0()
[SimHub (2).log](https://github.com/SHWotever/SimHub/files/5330685/SimHub.2.log)

**Comment by Romainrob** [comment]
Hi. 
First time I hear of this issue. In case this can help. Here is the script triggering the sounds: 
[SimHubSounds.zip](https://github.com/SHWotever/SimHub/files/5335127/SimHubSounds.zip)

**Comment by SHWotever** [comment]
Hi ! I've released a fix about a bad memory leak this should solve it.
