### ISSUE TITLE
SimHub not launching

### ISSUE THREAD

**Issue by v364** [SHWotever/SimHub#689]
Hello, I just installed SimHub on my laptop. When I want to run it, nothing happens - even if I try "run as administrator". I also have the newest version of .NET Framework. I also tried to download older version of SimHub, but nothing changes. 
Could you help me, please? Thanks

**Comment by SHWotever** [comment]
Hi ! Do you have the simhub log file ? It's located into the logs folder inside simhub install directory

**Comment by v364** [comment]
[SimHub.log](https://github.com/SHWotever/SimHub/files/5433552/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! Thanks for the log, it shows that a critical module can't load, it often happens when c++ is corrupted, 

Make sure to install/repair all the dependencies listed here : https://www.microsoft.com/en-us/download/details.aspx?id=56116
https://www.microsoft.com/en-us/download/details.aspx?id=40784 (both x86 and x64, you don't need arm version)
https://www.microsoft.com/en-us/download/details.aspx?id=53840 (both x86 and x64, you don't need arm version)

If the installer says it's already installed ( it should be as Simhub has it embedded with the installer) hit repair to make sure it's correctly installed.

If somehow this is not enough it means that your windows install is corrupted deeper, in this case a proper windows reinstall can solve it.

**Comment by v364** [comment]
Thanks for help :) I'll try this

**Comment by NateCroix** [comment]
> 
> If somehow this is not enough it means that your windows install is corrupted deeper, in this case a proper windows reinstall can solve it.

This is a bit of a cop-out no? I've been having this issue with SimHub specifically with zero issues for other programs on my PC, including VS dev environments that use some of the same dependencies. It would be nice if there was a different option than "reinstall windows" which is a major life-upsetting task for some of us using highly developed windows environments. (Id rather move house than reinstall windows)

**Comment by NateCroix** [comment]
After totally removing all simhub folders on system post uninstall, reinstalling all dependencies, running cmdline image repair & sfc/scannow I was able to get simhub open without launching ACC first, but it still hangs once ACC is selected in game tab regardless if ACC is open or not first. 

> [2021-04-29 13:59:11,449] INFO - Starting SimHub v7.3.14 (build time : 17/04/2021 23:46:09)
[2021-04-29 13:59:11,450] INFO - Administrator privileges : True 
[2021-04-29 13:59:11,450] INFO - OS version : Microsoft Windows NT 10.0.19041.0, Windows 10.0.19041
[2021-04-29 13:59:11,450] INFO - License status : Licensed
[2021-04-29 13:59:11,450] INFO - Process priority : Normal
[2021-04-29 13:59:11,632] ERROR - First chance exception error System.InvalidOperationException: Property 'UriSource' or property 'StreamSource' must be set.
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
[2021-04-29 13:59:11,632] ERROR - First chance exception error System.Xaml.XamlObjectWriterException: Initialization of 'System.Windows.Media.Imaging.BitmapImage' threw an exception. ---> System.InvalidOperationException: Property 'UriSource' or property 'StreamSource' must be set.
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
   --- End of inner exception stack trace ---
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)
[2021-04-29 13:59:11,952] INFO - (Re)Starting ATS Game Manager and plugin manager
[2021-04-29 13:59:11,952] INFO - Creating American Truck Simulator game manager (ETS2Reader.ATSManagerV2)
[2021-04-29 13:59:11,957] INFO - ATS game manager created
[2021-04-29 13:59:11,960] INFO - Checking configuration status for ATS
[2021-04-29 13:59:11,960] INFO - Configuration status for ATS: GameNotDetected
[2021-04-29 13:59:11,961] INFO - Creating plugin manager with plugins : SerialDashPlugin, AudioControlPlugin, JoystickPlugin, GraphicalDashPlugin, KeyboardEmulatorPlugin, NextionPlugin, ShakeITBSV3Plugin, ShakeITMotorsV3Plugin, LapHitoryPlugin, ThrustmastersPlugin
[2021-04-29 13:59:11,968] INFO - Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2021-04-29 13:59:11,969] INFO - Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2021-04-29 13:59:11,969] INFO - Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2021-04-29 13:59:11,969] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2021-04-29 13:59:11,969] INFO - Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2021-04-29 13:59:11,970] INFO - Creating SimHub.Plugins.Web.WebPlugin plugin
[2021-04-29 13:59:11,970] INFO - Creating SimHub.Plugins.AudioControl.AudioControlPlugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.InputPlugins.JoystickPlugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
[2021-04-29 13:59:11,973] INFO - Creating SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
[2021-04-29 13:59:11,973] INFO - Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2021-04-29 13:59:12,335] INFO - Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2021-04-29 13:59:12,385] INFO - Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2021-04-29 13:59:12,386] INFO - Initialising SimHub.Plugins.AudioControl.AudioControlPlugin plugin
[2021-04-29 13:59:12,386] INFO - Initialising SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin plugin
[2021-04-29 13:59:12,623] ERROR - First chance exception error System.DllNotFoundException: Unable to load DLL 'nvml.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at PInvokeDelegateFactoryInternalWrapperType46.nvmlInit_v2()
   at OpenHardwareMonitor.Hardware.Nvidia.NVML.NvmlInit()
[2021-04-29 13:59:12,623] ERROR - First chance exception error System.DllNotFoundException: Unable to load DLL 'nvml.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at PInvokeDelegateFactoryInternalWrapperType45.nvmlInit()
   at OpenHardwareMonitor.Hardware.Nvidia.NVML.NvmlInit()
[2021-04-29 13:59:12,656] INFO - Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin
[2021-04-29 13:59:12,928] INFO - Initialising SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin
[2021-04-29 13:59:12,950] INFO - Initialising SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin plugin
[2021-04-29 13:59:12,950] INFO - Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2021-04-29 13:59:12,951] INFO - Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2021-04-29 13:59:12,951] INFO - Initialising SimHub.Plugins.InputPlugins.JoystickPlugin plugin
[2021-04-29 13:59:12,972] INFO - Initialising SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin plugin
[2021-04-29 13:59:12,975] INFO - Initialising SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin plugin
[2021-04-29 13:59:13,017] INFO - JoystickManager : Starting game controllers detection
[2021-04-29 13:59:13,024] INFO - Initialising SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin
[2021-04-29 13:59:13,073] INFO - JoystickManager : End of detection
[2021-04-29 13:59:13,092] INFO - Loading font list
[2021-04-29 13:59:13,241] INFO - Initialising SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin
[2021-04-29 13:59:13,313] INFO - Starting Arduino in Single USB mode
[2021-04-29 13:59:13,318] INFO - Matrix custom font custommatrixfont8x8 loaded
[2021-04-29 13:59:13,318] INFO - Initialising SimHub.Plugins.Web.WebPlugin plugin
[2021-04-29 13:59:13,427] INFO - Web suggested IP :192.168.0.6
[2021-04-29 13:59:13,555] INFO - Font list loading successful
[2021-04-29 13:59:13,561] INFO - Web available IPs :10.5.0.2,192.168.0.6
[2021-04-29 13:59:13,564] INFO - Web font-faces up to date
[2021-04-29 13:59:13,564] INFO - Plugin manager correctly initialised
[2021-04-29 13:59:13,565] INFO - Loading plugins controls
[2021-04-29 13:59:13,833] INFO - Game successfully loaded
[2021-04-29 13:59:15,002] INFO - Maximizing dash to monitor \\.\DISPLAY2 : bounds: {X=-2560,Y=0,Width=2560,Height=1440}, pos top: 288, pos left: -2048, width: 1536, height: 864 
Available monitors : \\.\DISPLAY1 : {X=0,Y=0,Width=2560,Height=1440}, primary True
\\.\DISPLAY2 : {X=-2560,Y=0,Width=2560,Height=1440}, primary False
[2021-04-29 13:59:42,580] INFO - Window destroyed
[2021-04-29 14:00:21,007] INFO - Checking configuration status for ATS
[2021-04-29 14:00:21,007] INFO - Configuration status for ATS: GameNotDetected
[2021-04-29 14:00:28,403] INFO - (Re)Starting AssettoCorsaCompetizione Game Manager and plugin manager
[2021-04-29 14:00:28,403] INFO - Stopping old game manager
[2021-04-29 14:00:28,405] INFO - Stopping old plugin manager
[2021-04-29 14:00:28,406] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
[2021-04-29 14:00:28,407] INFO - SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin settings saved
[2021-04-29 14:00:28,407] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.SystemInfosProvider
[2021-04-29 14:00:28,421] INFO - SimHub.Plugins.DataPlugins.SystemInfosProvider plugin settings saved
[2021-04-29 14:00:28,421] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2021-04-29 14:00:28,443] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin settings saved
[2021-04-29 14:00:28,443] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2021-04-29 14:00:28,448] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin settings saved
[2021-04-29 14:00:28,448] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin
[2021-04-29 14:00:28,458] INFO - SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin plugin settings saved
[2021-04-29 14:00:28,458] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2021-04-29 14:00:28,466] INFO - SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin settings saved
[2021-04-29 14:00:28,466] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin
[2021-04-29 14:00:28,482] INFO - SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin settings saved
[2021-04-29 14:00:28,482] INFO - Stopping plugin SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
[2021-04-29 14:00:28,482] INFO - Stopping plugin SimHub.Plugins.DataPlugins.SystemInfosProvider
[2021-04-29 14:00:28,527] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin
[2021-04-29 14:00:28,527] INFO - Stopping plugin SimHub.Plugins.AudioControl.AudioControlPlugin
[2021-04-29 14:00:28,579] INFO - Stopping plugin SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin
[2021-04-29 14:00:28,579] INFO - Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2021-04-29 14:00:28,580] INFO - Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2021-04-29 14:00:28,580] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin
[2021-04-29 14:00:28,580] INFO - Stopping plugin SimHub.Plugins.AudioControl.AudioPlayPlugin
[2021-04-29 14:00:28,580] INFO - Stopping plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin
[2021-04-29 14:00:28,580] INFO - Stopping plugin SimHub.Plugins.InputPlugins.JoystickPlugin
[2021-04-29 14:00:28,580] INFO - Stopping plugin SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin
[2021-04-29 14:00:28,580] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin
[2021-04-29 14:00:28,583] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2021-04-29 14:00:28,585] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin
[2021-04-29 14:00:28,586] INFO - Stopping plugin SimHub.Plugins.Web.WebPlugin
[2021-04-29 14:00:28,586] INFO - Stopped all plugins
[2021-04-29 14:00:28,587] INFO - Creating Assetto Corsa Competizione game manager (ACSharedMemory.ACCManager)
[2021-04-29 14:00:28,587] INFO - AssettoCorsaCompetizione game manager created
[2021-04-29 14:00:28,587] INFO - Setting listening UDP to 9000
[2021-04-29 14:00:28,588] ERROR - First chance exception error System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 127.0.0.1:9000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
[2021-04-29 14:00:28,589] ERROR - First chance exception error System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 127.0.0.1:9000
   at System.Net.Sockets.UdpClient.Connect(String hostname, Int32 port)
[2021-04-29 14:00:28,589] ERROR - Error while loading game manager
System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 127.0.0.1:9000
   at System.Net.Sockets.UdpClient.Connect(String hostname, Int32 port)
   at ksBroadcastingNetwork.ACCUdpRemoteClient..ctor(String ip, Int32 port, String displayName, String connectionPassword, String commandPassword, Int32 msRealtimeUpdateInterval)
   at ACSharedMemory.ACCManager.set_UDPPort(Int32 value)
   at SimHubWPF.MainWindow.<>c__DisplayClass42_0.<ChangeGame>b__3()
[2021-04-29 14:00:28,590] ERROR - First chance exception error System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 127.0.0.1:9000
   at System.Net.Sockets.UdpClient.Connect(String hostname, Int32 port)
   at ksBroadcastingNetwork.ACCUdpRemoteClient..ctor(String ip, Int32 port, String displayName, String connectionPassword, String commandPassword, Int32 msRealtimeUpdateInterval)
   at ACSharedMemory.ACCManager.set_UDPPort(Int32 value)
   at SimHubWPF.MainWindow.<>c__DisplayClass42_0.<ChangeGame>b__3()
[2021-04-29 14:00:28,591] ERROR - First chance exception error System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 127.0.0.1:9000
   at System.Net.Sockets.UdpClient.Connect(String hostname, Int32 port)
   at ksBroadcastingNetwork.ACCUdpRemoteClient..ctor(String ip, Int32 port, String displayName, String connectionPassword, String commandPassword, Int32 msRealtimeUpdateInterval)
   at ACSharedMemory.ACCManager.set_UDPPort(Int32 value)
   at SimHubWPF.MainWindow.<>c__DisplayClass42_0.<ChangeGame>b__3()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[2021-04-29 14:00:28,591] ERROR - Error while loading game manager
System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 127.0.0.1:9000
   at System.Net.Sockets.UdpClient.Connect(String hostname, Int32 port)
   at ksBroadcastingNetwork.ACCUdpRemoteClient..ctor(String ip, Int32 port, String displayName, String connectionPassword, String commandPassword, Int32 msRealtimeUpdateInterval)
   at ACSharedMemory.ACCManager.set_UDPPort(Int32 value)
   at SimHubWPF.MainWindow.<>c__DisplayClass42_0.<ChangeGame>b__3()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at SimHubWPF.MainWindow.ChangeGame(SupportedGameManager game)
[2021-04-29 14:00:29,596] INFO - AC shared memory connected
[2021-04-29 14:00:35,175] INFO - Application exit
[2021-04-29 14:00:35,186] INFO - Stopping game manager
[2021-04-29 14:00:35,187] INFO - Stopping plugin manager
[2021-04-29 14:00:35,187] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
[2021-04-29 14:00:35,187] INFO - SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin settings saved
[2021-04-29 14:00:35,187] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.SystemInfosProvider
[2021-04-29 14:00:35,191] INFO - SimHub.Plugins.DataPlugins.SystemInfosProvider plugin settings saved
[2021-04-29 14:00:35,191] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2021-04-29 14:00:35,191] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin plugin settings saved
[2021-04-29 14:00:35,192] INFO - Saving plugin settings SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2021-04-29 14:00:35,192] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin plugin settings saved
[2021-04-29 14:00:35,192] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin
[2021-04-29 14:00:35,195] INFO - SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin plugin settings saved
[2021-04-29 14:00:35,195] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2021-04-29 14:00:35,199] INFO - SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin plugin settings saved
[2021-04-29 14:00:35,199] INFO - Saving plugin settings SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin
[2021-04-29 14:00:35,201] INFO - SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin plugin settings saved
[2021-04-29 14:00:35,201] INFO - Stopping plugin SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin
[2021-04-29 14:00:35,201] INFO - Stopping plugin SimHub.Plugins.DataPlugins.SystemInfosProvider
[2021-04-29 14:00:35,201] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin
[2021-04-29 14:00:35,201] INFO - Stopping plugin SimHub.Plugins.AudioControl.AudioControlPlugin
[2021-04-29 14:00:35,201] INFO - Stopping plugin SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2021-04-29 14:00:35,202] INFO - Finalizing plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2021-04-29 14:00:35,202] INFO - Finalizing plugin SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.AudioControl.AudioPlayPlugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin
[2021-04-29 14:00:35,202] INFO - Finalizing plugin SimHub.Plugins.DataPlugins.Shell.ShellPlugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.InputPlugins.JoystickPlugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.KeyboardEmulator.KeyboardEmulatorPlugin
[2021-04-29 14:00:35,202] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin
[2021-04-29 14:00:35,203] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2021-04-29 14:00:35,204] INFO - Finalizing plugin SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin
[2021-04-29 14:00:35,205] INFO - Stopping plugin SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin
[2021-04-29 14:00:35,205] INFO - Stopping plugin SimHub.Plugins.Web.WebPlugin
[2021-04-29 14:00:35,205] INFO - Finalizing plugin SimHub.Plugins.Web.WebPlugin
[2021-04-29 14:00:35,205] INFO - Stopped all plugins
[2021-04-29 14:00:35,205] INFO - Performance dump
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITBSV3Plugin::DataUpdate	4472calls	158.009ms	4472calls	0.035ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.DataPlugins.Thrustmaster.ThrustmastersPlugin::DataUpdate	4472calls	1.205ms	4472calls	0.000ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.OutputPlugins.Dash.SerialDashPlugin::DataUpdate	4472calls	151.023ms	4472calls	0.034ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.AudioControl.AudioControlPlugin::DataUpdate	4472calls	128.103ms	4472calls	0.029ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.OutputPlugins.GraphicalDash.GraphicalDashPlugin::DataUpdate	4472calls	46.548ms	4472calls	0.010ms/call
[2021-04-29 14:00:35,205] INFO - MultipleSerialDashPlugin::WorkerLoop	4472calls	40.148ms	4472calls	0.009ms/call
[2021-04-29 14:00:35,205] INFO - JoystickPlugin::PollThread	3608calls	50.935ms	3608calls	0.014ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.DataPlugins.PersistantTracker.LapHitoryPlugin::DataUpdate	4472calls	0.916ms	4472calls	0.000ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.DataPlugins.ShakeItV3.ShakeITMotorsV3Plugin::DataUpdate	4472calls	52.877ms	4472calls	0.012ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin::DataUpdate	4472calls	166.145ms	4472calls	0.037ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.OutputPlugins.Nextion.NextionPlugin::DataUpdate	4472calls	1.427ms	4472calls	0.000ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.Web.WebPlugin::DataUpdate	4472calls	67.871ms	4472calls	0.015ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin::DataUpdate	4472calls	23.022ms	4472calls	0.005ms/call
[2021-04-29 14:00:35,205] INFO - JoystickManager::DetectJoysticks	1calls	112.950ms	1calls	112.950ms/call
[2021-04-29 14:00:35,205] INFO - SimHub.Plugins.DataPlugins.SystemInfosProvider::DataUpdate	4472calls	13.999ms	4472calls	0.003ms/call
[2021-04-29 14:00:35,205] INFO - Final Exit
