### ISSUE TITLE
Persistent Tracker Plugin broken for Live for Speed

### ISSUE THREAD

**Issue by TagForce** [SHWotever/SimHub#762]
I noticed, while adding LFS support to my 'every game I own' F1 dash, that every time I complete a lap in LFS, the persistent tracker plugin throws an error in the logs:

```
[2021-03-07 00:04:18,787] WARN - System.NullReferenceException: Object reference not set to an instance of an object.
   at SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin.FillRecordData(Int32 completedLapNumber, GameData data, DataRecord record)
   at SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin.manager_NewLap(Int32 completedLapNumber, Boolean testLap, PluginManager manager, GameData& data)
   at SimHub.Plugins.PluginManager.NewLapDelegate.Invoke(Int32 completedLapNumber, Boolean testLap, PluginManager manager, GameData& data)
   at SimHub.Plugins.PluginManager.manager_NewLap(Int32 completedLapNumber, Boolean testLap, IGameManager manager)
   at GameReaderCommon.GameManagerBase`3.RaiseNewLap(Int32 completedLapNumber, Boolean testLap)
   at GameReaderCommon.GameManagerBase`3.<>c__DisplayClass341_0.<CheckLapChanged>b__0()
   at GameReaderCommon.GameManagerBase`3.SecureDo(Action a)
```

This happens every time I complete a lap. The PersistentTrackerPlugin.PreviousLap_00 value never changes.
Since GameData.LastLaptime is unsupported for LFS, I need the PersistentTrackerPlugin.PreviousLap values to trigger my dash events, but can't.

**Comment by SHWotever** [comment]
Hi ! I've released a full update of LFS telemetry, inclusind support of last lap and a fix for this error. 

Nicolas

**Comment by TagForce** [comment]
Thanks. The error is gone, and it's actually outputting some information now.

However. It seems that the laptimes are recorded for each and every driver on the track, and not just the player.
Gamedata.LastLapTime is updated for every driver that crosses the line.

**Comment by SHWotever** [comment]
Hi ! Indeed I tested offline, but when I went online everything went mixed. I've fixed it in the last release and extendly tested it both offline and online. 

That said there is one big limitation remaining the current lap time can be only guessed correctly after having past the first split or lap (it's a limitation if the LFS "telemetry" model). 

Concerning the engine temps, indeed the data is "available" in telemetry and ready to go in simhub, but LFS does not simulates it yet so the data given by the game is always 0 : the question is old but it haven't changed yet : https://www.lfs.net/forum/thread/81214-Outgauge-data-format---issue

**Comment by TagForce** [comment]
Thank you very much :) You're the bomb!

> Concerning the engine temps, indeed the data is "available" in telemetry and ready to go in simhub, but LFS does not simulates it yet so the data given by the game is always 0 : the question is old but it haven't changed yet : https://www.lfs.net/forum/thread/81214-Outgauge-data-format---issue

Oh my god! I've been playing LFS ever since the West Brothers' 'Racing Legends' went vaporware, and I never noticed that the engine temp gauge actually shows FPS in game!

I will test it this evening, and close the issue when it all works.
