### ISSUE TITLE
Problem with bluetooth serial device

### ISSUE THREAD

**Issue by Metaln00b** [SHWotever/SimHub#809]
I got an error after a successful connection. Sometimes simhub hangs up after toogle the "Connected" radio button do "Disabled". There is also an issue at the display of the button state.
```
[2021-05-01 00:04:17,582] INFO - Starting SimHub v7.3.14 (build time : 18/04/2021 08:46:09)
[2021-05-01 00:04:17,583] INFO - Administrator privileges : True 
[2021-05-01 00:04:17,583] INFO - OS version : Microsoft Windows NT 10.0.19042.0, Windows 10.0.19042
[2021-05-01 00:04:17,583] INFO - License status : Licensed
[2021-05-01 00:04:17,583] INFO - Process priority : Normal
[2021-05-01 00:04:18,223] INFO - (Re)Starting F12020 Game Manager and plugin manager
[2021-05-01 00:04:18,224] INFO - Creating Codemasters F1 2020 game manager (CodemastersReader.CodemastersF12020Manager)
[2021-05-01 00:04:18,251] INFO - F12020 game manager created
[2021-05-01 00:04:18,251] INFO - Setting listening UDP to 20777
[2021-05-01 00:04:18,262] INFO - Checking configuration status for F12020
[2021-05-01 00:04:18,279] INFO - Configuration status for F12020: GameConfigured
[2021-05-01 00:04:18,279] INFO - Creating plugin manager with plugins : CustomSerialPlugin
[2021-05-01 00:04:18,298] INFO - Creating SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2021-05-01 00:04:18,299] INFO - Creating SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2021-05-01 00:04:18,299] INFO - Creating SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2021-05-01 00:04:18,299] INFO - Creating SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2021-05-01 00:04:18,299] INFO - Creating SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2021-05-01 00:04:18,300] INFO - Creating SimHub.Plugins.Web.WebPlugin plugin
[2021-05-01 00:04:18,300] INFO - Creating SimHub.Plugins.OutputPlugins.SerialComm.CustomSerialPlugin plugin
[2021-05-01 00:04:18,301] INFO - Initialising SimHub.Plugins.DataPlugins.DataCore.DataCorePlugin plugin
[2021-05-01 00:04:18,958] INFO - Initialising SimHub.Plugins.DataPlugins.SystemInfosProvider plugin
[2021-05-01 00:04:19,005] INFO - Initialising SimHub.Plugins.DataPlugins.PersistantTracker.PersistantTrackerPlugin plugin
[2021-05-01 00:04:19,005] INFO - Initialising SimHub.Plugins.AudioControl.AudioPlayPlugin plugin
[2021-05-01 00:04:19,007] INFO - Initialising SimHub.Plugins.DataPlugins.Shell.ShellPlugin plugin
[2021-05-01 00:04:19,008] INFO - Initialising SimHub.Plugins.OutputPlugins.SerialComm.CustomSerialPlugin plugin
[2021-05-01 00:04:19,056] INFO - Initialising SimHub.Plugins.Web.WebPlugin plugin
[2021-05-01 00:04:19,193] INFO - Web suggested IP :192.168.178.52
[2021-05-01 00:04:19,260] INFO - Web font-faces up to date
[2021-05-01 00:04:19,261] INFO - Plugin manager correctly initialised
[2021-05-01 00:04:19,261] INFO - Loading plugins controls
[2021-05-01 00:04:19,358] INFO - Game successfully loaded
[2021-05-01 00:04:37,359] INFO - Game connected
[2021-05-01 00:04:40,442] INFO - Game paused : true
[2021-05-01 00:04:41,213] ERROR - Could not connect to serial device System.IO.IOException: Kein Prozess ist am anderen Ende der Pipe.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Ports.SerialStream.Write(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialPort.Write(String text)
   at SimHub.Plugins.OutputPlugins.SerialComm.SerialWorker.<ProcessSerial>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.Plugins.OutputPlugins.SerialComm.SerialWorker.<<DataUpdate>b__10_0>d.MoveNext()
[2021-05-01 00:05:04,142] INFO - Game paused : false
[2021-05-01 00:05:11,458] ERROR - Could not connect to serial device System.IO.IOException: Kein Prozess ist am anderen Ende der Pipe.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Ports.SerialStream.Write(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialPort.Write(String text)
   at SimHub.Plugins.OutputPlugins.SerialComm.SerialWorker.<ProcessSerial>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.Plugins.OutputPlugins.SerialComm.SerialWorker.<<DataUpdate>b__10_0>d.MoveNext()
[2021-05-01 00:05:11,742] INFO - Game paused : true
[2021-05-01 00:05:34,559] INFO - Game paused : false
[2021-05-01 00:05:40,209] INFO - Game paused : true
[2021-05-01 00:05:41,688] ERROR - Could not connect to serial device System.IO.IOException: Kein Prozess ist am anderen Ende der Pipe.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Ports.SerialStream.Write(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialPort.Write(String text)
   at SimHub.Plugins.OutputPlugins.SerialComm.SerialWorker.<ProcessSerial>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SimHub.Plugins.OutputPlugins.SerialComm.SerialWorker.<<DataUpdate>b__10_0>d.MoveNext()
```

![Screenshot 2021-05-01 001214](https://user-images.githubusercontent.com/25951169/116759186-09792680-aa12-11eb-9922-1fe2db84ec97.png)

**Comment by SHWotever** [comment]
Hi ! Thanks for the feedback, I will fix the display error,

Concerning the broken pipe error it seems to be a common error related to bluetooth serial ports (like hc-05 modules etc...), from my understanding it does not occur on simhub side but it's reported by windows so I it's not something I should be able to fix on on my end, have you tried with a simple serial terminal in order to check that serial port was properly working ?

I already played with bluetooth devices (like HC-05) in the past and similar errors where quite commons, that's why I will never port simhub to support natively bluetooth unfortunately, it's too unstable unfrtunately.

**Comment by Metaln00b** [comment]
Hi! Thank you for the fast response. At first, i love Simhub =) 

> Hi ! Thanks for the feedback, I will fix the display error,

Do you know why SimHub is freezing after click on close also? The timeout exception already works, but only as long as I don't try to close Simhub, because then it freezes.
 
> Concerning the broken pipe error it seems to be a common error related to bluetooth serial ports (like hc-05 modules etc...), from my understanding it does not occur on simhub side but it's reported by windows so I it's not something I should be able to fix on on my end, have you tried with a simple serial terminal in order to check that serial port was properly working ?

I have checked the connection with serial terminal, it is also be broken. For the last time, the BT was very stable. It could be an issue with the bluetooth interface of the Windows API you mean?
Or should i send "NOP" messages back? Could it be possible, that RTS or DTR is disturbing the connection?
> 
> I already played with bluetooth devices (like HC-05) in the past and similar errors where quite commons, that's why I will never port simhub to support natively bluetooth unfortunately, it's too unstable unfrtunately.

It would be nice if a custom udp protocol could be possible, but you work is already so perfect =)
