### ISSUE TITLE
Dirt Rally 2.0 - Session odo incorrect

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#888]
Hi,

DataCorePlugin.GameData.SessionOdo goes instantly from 0 to a very large value as soon as the game connects when the stage countdown starts.

Suite à notre échange sur discord.
J'ai testé ce soir un peu plus pour sessionodo, d'où le ce ticket.

En passant DR 2.0 se déconnecte bien pendant la pause ou les replays.
Je crois me souvenir d'un jeu ou les shakers fonctionnaient pendant les replays, je ne souviens pas duquel...

Bonne soirée.

**Comment by Romainrob** [comment]
I just noticed the logs are file with this errors:

[2021-07-30 20:50:17,092] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at CodemastersReader.CodemastersManager.GetNewRawData()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
[2021-07-30 20:50:17,106] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at CodemastersReader.CodemastersManager.GetNewRawData()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
[2021-07-30 20:50:17,122] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at CodemastersReader.CodemastersManager.GetNewRawData()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
      
[SimHub.log](https://github.com/SHWotever/SimHub/files/6909605/SimHub.log)

**Comment by herve4545** [comment]
Hello
C'est quoi sessionOdo ?
Merci

**Comment by Romainrob** [comment]
Salut,
Odo pour odomètre.
C'est le compteur kilométrique de la session en cours.

**Comment by E66666666** [comment]
Suffering from the same issue here.

```
[2021-08-06 00:31:49,263] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at CodemastersReader.CodemastersManager.GetNewRawData()
   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
[repeat ad infinum]
```

**Comment by SHWotever** [comment]
Hello ! Les deux problèmes sont corrigés pour la prochaine version !
