### ISSUE TITLE
Replays - Error when looping

### ISSUE THREAD

**Issue by Romainrob** [SHWotever/SimHub#932]
**Describe the bug**
Salut,
Depuis la version 7.4.7, c'est un vrai bonheur de charger des replays. Merci encore pour ça!
Par contre en fin de replay, quand il boucle, j'ai une erreur dans les logs. 
Constaté avec ACC et iRacing, avec des vieux et nouveaux replays.

[2021-09-28 20:28:55,336] INFO - Allocating FMOD output for CSL - Shakers (USB Sound Device)
[2021-09-28 20:28:58,967] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at IRacingReader.IRacingManager.DeSerialize(DataSampleStorage& value)
   at GameReaderCommon.GameManagerBase`3.ReplayLoop()
[2021-09-28 20:28:58,982] INFO - Replay restarted

[2021-09-28 20:22:13,228] INFO - Allocating FMOD output for CSL - Shakers (USB Sound Device)
[2021-09-28 20:22:14,195] ERROR - System.NullReferenceException: Object reference not set to an instance of an object.
   at ACSharedMemory.ACCManager.GD_CurrentSectorIndex()
   at ACSharedMemory.ACCManager.PreParseData()
   at GameReaderCommon.GameManagerBase`3.ReplayLoop()
[2021-09-28 20:22:14,211] INFO - Replay restarted

**Simhub version**
7.4.7 et 7.4.8b2

**To Reproduce**
Jouer la fin replay pour qu'il boucle.

**Log files**
[SimHub.log](https://github.com/SHWotever/SimHub/files/7246549/SimHub.log)

**Additional context**
Je ne constate pas d'effet particulier, juste l'erreur dans les logs.
J'ai pensé que ça pourrait t’intéresser.
Bonne soirée et bonne chasse! ;)

**Comment by SHWotever** [comment]
Well seen, a little mistake at the very end of the replay. It's fixed for the next release !

**Comment by SHWotever** [comment]
Duplicate of https://github.com/SHWotever/SimHub/issues/926
