### ISSUE TITLE
Usb crash

### ISSUE THREAD

**Issue by beastlyfern** [SHWotever/SimHub#937]
I have been having usb crashes again. It used to crash all my usb devices but I removed my wheel and pedals from the hub but my wind sim, leonardo (usb shifter control) and my micro mini (button) box still seem to crash. Because the wind sim is the first thing to crash in the log would it be assumed that this is the one causing the crash? They don't do it right away I was playing for about 30 mins before and it was not until I was in a race it started. 

Thanks again.

[SimHub.log](https://github.com/SHWotever/SimHub/files/7272658/SimHub.log)

**Comment by beastlyfern** [comment]
So I figured out it was the wind sim module. Not sure why, maybe because I am driving two fans and two xbox rumble motors with the same motor board. This might explain why it does not cut off right away but take time for the board to maybe overheat. Not sure. I did install a small fan on the box for the wind sim and will run it now. 

Do you think this is what is happening and is there anyway I can check to see if it is disconnecting because of overheating? 

Here is the most recent error I also attached the entire log:
[2021-10-03 21:13:05,522] INFO - Storing lap consumption : 0.99, lap start : 4.70, lap end : 3.70
[2021-10-03 21:15:45,037] INFO - New fuel stat aggregated 1.01/lap
[2021-10-03 21:15:45,538] INFO - CurrentLap invalidated for Fuel stats
[2021-10-03 21:15:51,704] INFO - Game disconnected
[2021-10-03 21:15:56,720] INFO - BassShakers: Requiring audio interfaces rebuild after game start or audio settings change
[2021-10-03 21:15:56,720] INFO - Disposing FMOD output for Speakers (Realtek(R) Audio)
[2021-10-03 21:15:56,837] INFO - Allocating FMOD output for Speakers (Realtek(R) Audio)
[2021-10-03 21:16:51,671] INFO - Game connected
[2021-10-03 21:16:51,696] INFO - All time best found : 00:02:35.5710000 recorded at 10/3/2021 9:07:50 PM
[2021-10-03 21:16:56,671] INFO - BassShakers: Requiring audio interfaces rebuild after game start or audio settings change
[2021-10-03 21:16:56,671] INFO - Disposing FMOD output for Speakers (Realtek(R) Audio)
[2021-10-03 21:16:56,787] INFO - Allocating FMOD output for Speakers (Realtek(R) Audio)
[2021-10-03 21:18:44,721] INFO - New fuel stat aggregated 1.04/lap
[2021-10-03 21:19:49,605] INFO - Forcing arduino sync
[2021-10-03 21:19:51,854] ERROR - Closing arduino Wind Sim@COM3 : reason System.IO.IOException: The I/O operation has been aborted because of either a thread exit or an application request.

   at System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   at System.IO.Ports.SerialStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Ports.SerialStream.Write(Byte[] array, Int32 offset, Int32 count, Int32 timeout)
   at System.IO.Ports.SerialPort.Write(String text)
   at ArqSerialLib.ArqSerial.SerialWrite(String data)
   at ArqSerialLib.ArqSerial.ReemitAll()
   at ArqSerialLib.ArqSerial.SynchronizeUpTo(Int32 aheadDatagrams)
   at ArqSerialLib.ArqSerial.FlushOutcoming(Boolean all)
   at SerialDash.SerialDashController.Send(Byte[] customMessage, Boolean capture)
[2021-10-03 21:19:51,854] INFO - Arduino performance report for Wind Sim@COM3 : Packetsize= 16, Packetbuffer = 1, SentDatagramsCount = 124964, FailedCount = 0, ReemitedCount = 1, ReemitedDuetoWait = 1, Current ahead = 1
[2021-10-03 21:19:51,854] INFO - Arduino performance report for Wind Sim@COM3 : Packetsize= 16, Packetbuffer = 1, SentDatagramsCount = 124964, FailedCount = 0, ReemitedCount = 1, ReemitedDuetoWait = 1, Current ahead = 1
[2021-10-03 21:20:06,381] INFO - Found one device on COM3 named {
  "ConnectedModel": "j",
  "Features": "GNIJPXV",
  "TM1638ModulesCount": 0,
  "UniqueId": "4d59002a-9f6c-4107-8bf9-2ecd4147dfa6",
  "DeviceName": "Wind Sim",
  "MotorsCount": 4,
  "PortName": "COM3",
  "HasBoost": 0,
  "HasSpeedo": 0,
  "IsBluetooth": false,
  "HasTacho": 0,
  "HasI2CLcd": false,
  "HasRGBMatrix": false,
  "ExpandedFeatures": [
    "mcutype",
    "keepalive",
    "Gear",
    "Motors"
  ],
  "MotorsBoard": "Adafruit Motor Shield V2",
  "MaxAheadDatagrams": 0,
  "DatagramMaxLength": 0,
  "MCUModel": "ATmega328P",
  "ReceivedDatagramsCount": 0
}
[2021-10-03 21:20:06,381] INFO - Switching device named Wind Sim to speed level 11 on COM3
[2021-10-03 21:20:06,381] INFO - Switching device on port COM3 to speed level 11, 115200 bauds
[2021-10-03 21:20:06,891] INFO - Connected to device on COM3 named Wind Sim
[2021-10-03 21:21:37,437] INFO - New fuel stat aggregated 1.08/lap
[2021-10-03 21:21:37,438] INFO - Old map quality score : 7 / New map quality score : 5
[2021-10-03 21:24:15,387] INFO - New fuel stat aggregated 1.02/lap
[2021-10-03 21:24:16,938] INFO - Old map quality score : 7 / New map quality score : 6
[2021-10-03 21:24:16,938] INFO - New session best recorded 00:02:37.9560000
[2021-10-03 21:24:16,938] INFO - Persistent tracker plugin TrackNewLap execution time : 1.2334ms
[2021-10-03 21:24:16,938] INFO - New valid lap detected {

I turned on the small fan after this and it did not disconnect again during that session. 
Any insight it very much appreciated. Thanks in advance. 

[SimHub.log](https://github.com/SHWotever/SimHub/files/7275387/SimHub.log)

**Comment by SHWotever** [comment]
Hi ! I don't think this is the cause, overheating boards don't cause all USB devices to fail, the motor will simply shutdown for a few seconds (it's even more in the milliseconds range) time for the chip to cooldown. I would seek for bad contacts, bad cables or maybe usb hubs.
