### ISSUE TITLE
SimHub hangs on startup on "Searching got game readers".

### ISSUE THREAD

**Issue by IlyaKochnev** [SHWotever/SimHub#998]
**Describe the bug**
SimHub hangs on the startup splash screen on "Searching got game readers".
There is an error in log "ERROR - Unhandled dispatcher errorSystem.IO.IOException: A device which does not exist was specified."

**Simhub version**
v7.4.16 (build time : 09/12/2021 09:53:20)

**To Reproduce**
Just upgraded from the previous version

**Log files**
```
[2022-01-05 11:27:53,703] INFO - Starting SimHub v7.4.16 (build time : 09/12/2021 09:53:20)
[2022-01-05 11:27:53,703] INFO - Administrator privileges : False 
[2022-01-05 11:27:53,703] INFO - OS version : Microsoft Windows NT 10.0.19044.0, Windows 10.0.19044
[2022-01-05 11:27:53,703] INFO - License status : Free
[2022-01-05 11:27:53,703] INFO - Process priority : Normal
[2022-01-05 11:27:53,750] FATAL - System.IO.IOException: A device which does not exist was specified.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at GamePipeLib.Model.Steam.SteamLibrary.GenerateGames()
   at GamePipeLib.Model.Steam.SteamLibrary.get_Games()
   at GamePipeLib.Model.Steam.SteamLibrary.GetGameById(String id)
   at GamePipeLib.Model.Steam.SteamLibrary.GetGameOrBundleById(String id)
   at GamePipeLib.Model.Steam.SteamRoot.GetGame(String appId)
   at SimHubWPF.App.LoadReaders()
   at SimHubWPF.App.<App_Startup>d__10.MoveNext()
[2022-01-05 11:27:53,750] ERROR - Unhandled dispatcher errorSystem.IO.IOException: A device which does not exist was specified.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at GamePipeLib.Model.Steam.SteamLibrary.GenerateGames()
   at GamePipeLib.Model.Steam.SteamLibrary.get_Games()
   at GamePipeLib.Model.Steam.SteamLibrary.GetGameById(String id)
   at GamePipeLib.Model.Steam.SteamLibrary.GetGameOrBundleById(String id)
   at GamePipeLib.Model.Steam.SteamRoot.GetGame(String appId)
   at SimHubWPF.App.LoadReaders()
   at SimHubWPF.App.<App_Startup>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Additional context**
I tried to reinstall completely by deleting program files and user data.
Reverting to version 7.4.0 fixed the issue.
Installing v7.4.16 over version 7.4.0 worked.

**Comment by SHWotever** [comment]
Hi ! 
Based on the log it looks like there was an issue with your steam install directory not being accessible (maybe a removable disk ?)

I've fixed it for the next version to avoid that a corrupted steam installation prevents simhub startup.

**Comment by IlyaKochnev** [comment]
Hi,
your assumption seems to be correct. The problem was in degraded RAID in RO mode where some (not all of them) games were located. Making this array completely inaccessible solved the issue.
